import path from 'node:path';import os from 'node:os';
import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';
import {load,response,query} from './testLoader.js';import {harness} from './inMemoryModels.js';
import {checkEnvironment,envInteger} from '../src/utils/deployment.js';import * as security from '../src/utils/security.js';
import {coursePurchaseNotice,welcomeNotice,subscriptionNotice,inReminderWindow,sandboxEmailAllowed} from '../src/utils/subscriptionNotifications.js';
const uid='111111111111111111111111',iid='222222222222222222222222',oid='333333333333333333333333',other='444444444444444444444444',now=new Date('2026-10-03T12:00:00Z');
const student=()=>({_id:uid,role:'student',email:'learner@academy.test',name:'Student A',status:'active',emailVerified:false});
const invoice=()=>({_id:iid,user:uid,kind:'course',title:'Negotiation Skills',status:'paid',number:'SA-REAL-INVOICE',totalMinor:12000,currency:'USD',accessStartsAt:now,accessExpiresAt:new Date(+now+86400000*30)});
const order=()=>({_id:oid,user:uid,kind:'course',product:'negotiation-skills'});
async function env(values,fn){const old={};for(const [k,v]of Object.entries(values)){old[k]=process.env[k];if(v===undefined)delete process.env[k];else process.env[k]=v;}try{return await fn();}finally{for(const[k,v]of Object.entries(old))if(v===undefined)delete process.env[k];else process.env[k]=v;}}
function outbox({type='course_purchased',testMode=false,owner=uid,user=student()}={}){
 const inv={...invoice(),testMode},payload=type==='welcome'?welcomeNotice(user,now):coursePurchaseNotice(order(),inv,now);
 inv.user=owner;
 const h=harness({User:[user],Invoice:[inv],Subscription:[],StudentNotification:[{_id:oid,...payload,attempts:0,testMode}]});let result={accepted:['learner@academy.test'],rejected:[]},mailError=false;const calls=[];
 const api=load('../src/services/studentNotifications.js',{crypto,envInteger,StudentNotification:h.model('StudentNotification'),Invoice:h.model('Invoice'),Subscription:h.model('Subscription'),User:h.model('User'),subscriptionNotice,inReminderWindow,coursePurchaseNotice,welcomeNotice,sandboxEmailAllowed,frontendOrigin:()=> 'https://review.academy.test',sendAcademyEmail:async message=>{calls.push(message);if(mailError)throw new Error('secret SMTP credentials must never leak');return result;}},'({deliverStudentNotifications,queueWelcomeNotification,queueCourseConfirmation})');
 return {...h,api,calls,item:()=>h.state.data.StudentNotification[0],setResult:r=>result=r,setFailure:()=>mailError=true};
}
test('V60.7 individual course email uses verified invoice amount, title, user and receipt link',()=>{const n=coursePurchaseNotice(order(),invoice(),now);assert.equal(n.user,uid);assert.equal(n.invoice,iid);assert.match(n.message,/USD 120\.00/);assert.match(n.message,/Negotiation Skills/);assert.equal(n.link,'/billing?section=invoices&invoice='+iid);});
test('V60.7 a course notice refuses an invoice owned by another student',()=>assert.throws(()=>coursePurchaseNotice(order(),{...invoice(),user:other},now),/invoice required/));
test('V60.7 an unpaid invoice cannot generate congratulations',()=>assert.throws(()=>coursePurchaseNotice(order(),{...invoice(),status:'open'},now),/invoice required/));
test('V60.7 invoice identity, not course slug, deduplicates purchase notifications',()=>{const a=coursePurchaseNotice(order(),invoice(),now),b=coursePurchaseNotice({...order(),user:other},{...invoice(),_id:other,user:other},now);assert.notEqual(a.dedupeKey,b.dedupeKey);});
test('V60.7 welcome notices are user-owned and dedupe across retries',async()=>{const f=outbox({type:'welcome'});f.state.data.StudentNotification=[];await f.api.queueWelcomeNotification(student());await f.api.queueWelcomeNotification(student());assert.equal(f.state.data.StudentNotification.length,1);assert.equal(f.item().user,uid);assert.equal(f.item().subscription,undefined);});
test('V60.7 purchase email can send to a normal non-verification student account',async()=>env({REQUIRE_EMAIL_VERIFICATION:'false'},async()=>{const f=outbox();const r=await f.api.deliverStudentNotifications({now,limit:1});assert.equal(r.sent,1);assert.equal(f.calls[0].to,'learner@academy.test');assert.match(f.calls[0].subject,/Congratulations/);assert.match(f.calls[0].messageId,/@notifications\.singhacademy\.com>$/);assert.equal(f.item().emailState,'sent');}));
test('V60.7 durable welcome email is delivered without requiring a subscription',async()=>env({REQUIRE_EMAIL_VERIFICATION:'false'},async()=>{const f=outbox({type:'welcome'});assert.equal((await f.api.deliverStudentNotifications({now,limit:1})).sent,1);assert.match(f.calls[0].text,/Welcome|welcome/);assert.match(f.calls[0].text,/https:\/\/review.academy.test\/home/);}));
test('V60.7 invoice ownership is rechecked before sending course email',async()=>{const f=outbox({owner:other});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().emailState,'skipped');});
test('V60.7 blocked student receives no new purchase email',async()=>{const f=outbox({user:{...student(),status:'blocked'}});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().emailState,'skipped');});
test('V60.7 sandbox mail is opt-in and requires an exact allowlisted recipient',()=>{assert.equal(sandboxEmailAllowed('learner@academy.test',{}),false);assert.equal(sandboxEmailAllowed('other@academy.test',{SEND_SANDBOX_EMAILS:'true',DEPLOYMENT_STAGE:'review',SANDBOX_EMAIL_ALLOWLIST:'learner@academy.test'}),false);assert.equal(sandboxEmailAllowed('Learner@academy.test',{SEND_SANDBOX_EMAILS:'true',DEPLOYMENT_STAGE:'review',SANDBOX_EMAIL_ALLOWLIST:'learner@academy.test'}),true);});
test('V60.7 sandbox email remains disabled in live production, including implicit live stage',()=>{for(const stage of [{DEPLOYMENT_STAGE:'production'},{NODE_ENV:'production'}])assert.equal(sandboxEmailAllowed('learner@academy.test',{SEND_SANDBOX_EMAILS:'true',SANDBOX_EMAIL_ALLOWLIST:'learner@academy.test',...stage}),false);});
test('V60.7 an allowlisted sandbox test purchase gets explicitly labelled email',async()=>env({DEPLOYMENT_STAGE:'review',SEND_SANDBOX_EMAILS:'true',SANDBOX_EMAIL_ALLOWLIST:'learner@academy.test',REQUIRE_EMAIL_VERIFICATION:'false'},async()=>{const f=outbox({testMode:true});assert.equal((await f.api.deliverStudentNotifications({now,limit:1})).sent,1);assert.match(f.calls[0].subject,/Sandbox/);assert.match(f.calls[0].text,/no real money/);}));
test('V60.7 SMTP acceptance for a different recipient is not success',async()=>{const f=outbox();f.setResult({accepted:['someoneelse@academy.test']});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.item().emailState,'deferred');assert.equal(f.item().emailAcceptedAt,undefined);});
test('V60.7 failed SMTP defers without changing invoice payment or exposing credentials',async()=>{const f=outbox();f.setFailure();await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.item().emailState,'deferred');assert.equal(f.state.data.Invoice[0].status,'paid');assert.equal(f.item().lastError,'email_delivery_not_confirmed');assert.doesNotMatch(f.item().lastError,/secret/);});
test('V60.7 console preview is not counted as SMTP sent',async()=>{const f=outbox();f.setResult({dev:true});const result=await f.api.deliverStudentNotifications({now,limit:1});assert.equal(result.sent,0);assert.equal(result.previewed,1);assert.equal(f.item().emailState,'dev_preview');});
test('V60.7 repeated delivery run does not resend an acknowledged course message',async()=>{const f=outbox();await f.api.deliverStudentNotifications({now,limit:1});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,1);});
const review=()=>({NODE_ENV:'production',DEPLOYMENT_STAGE:'review',AUTH_SECRET:crypto.randomBytes(48).toString('hex'),MFA_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),MONGODB_URI:'mongodb://127.0.0.1:27017/test?replicaSet=rs0',FRONTEND_URL:'https://review.academy.test',FRONTEND_URLS:'https://review.academy.test',PUBLIC_API_URL:'/api',REQUIRE_ADMIN_MFA:'true',SMTP_HOST:'smtp.academy.test',EMAIL_FROM:'mail@academy.test',UPLOADS_ENABLED:'false',UPLOAD_SCAN_REQUIRED:'false'});
test('V60.7 public review can disable all uploads while retaining production session/security defaults',()=>assert.deepEqual(checkEnvironment(review()).errors,[]));
test('V60.10 review accepts retired MFA flags without weakening other checks',()=>assert.deepEqual(checkEnvironment({...review(),REQUIRE_ADMIN_MFA:'false'}).errors,[]));
test('V60.7 enabling review uploads still requires real scanner configuration',()=>assert.ok(checkEnvironment({...review(),UPLOADS_ENABLED:'true'}).errors.some(x=>x.includes('CLAMAV'))));
test('V60.7 live production cannot use the review uploads-disabled scanner exception',()=>assert.ok(checkEnvironment({...review(),DEPLOYMENT_STAGE:'production'}).errors.some(x=>x.includes('CLAMAV'))));
test('V60.7 sandbox mail configuration refuses unbounded recipients and live stage',()=>{assert.ok(checkEnvironment({...review(),SEND_SANDBOX_EMAILS:'true'}).errors.some(x=>x.includes('ALLOWLIST')));assert.ok(checkEnvironment({...review(),DEPLOYMENT_STAGE:'production',SEND_SANDBOX_EMAILS:'true',SANDBOX_EMAIL_ALLOWLIST:'learner@academy.test'}).errors.some(x=>x.includes('sandbox emails')));});
test('V60.7 hosted review cookies are Secure even if a legacy environment still says development',async()=>env({NODE_ENV:'development',DEPLOYMENT_STAGE:'review'},async()=>assert.equal(security.cookieOptions('student').secure,true)));
test('V60.7 upload admission blocks before any upload parser or file write when disabled',async()=>env({UPLOADS_ENABLED:'false'},async()=>{const multer=Object.assign(()=>({single:()=>()=>{throw new Error('Parser must not run');}}),{diskStorage:()=>({})});const admit=load('../src/services/uploads.js',{path,os,fs:{mkdirSync(){}},multer,envInteger},'uploadAdmission');const res=response();let next=false;admit({},res,()=>next=true);assert.equal(res.code,503);assert.equal(res.body.code,'UPLOADS_DISABLED');assert.equal(next,false);}));
test('V60.7 verified session lookup is shared only inside one request, never across users or requests',async()=>{
 let sessionQueries=0,userQueries=0;const user={...student(),tokenVersion:0},session={_id:oid,user:uid,portal:'student',lastSeenAt:new Date(),revokedAt:null};
 const api=load('../src/middleware/auth.js',{...security,AuthSession:{findOne:()=>{sessionQueries++;return query(session);}},User:{findById:()=>{userQueries++;return query(user);}},isSessionUsable:()=>true},'({resolveSession})');
 const req={cookies:{[security.COOKIE_NAMES.student]:'a'.repeat(64)}};
 const [a,b]=await Promise.all([api.resolveSession(req,'student'),api.resolveSession(req,'student')]);assert.ok(a);assert.equal(a,b);assert.equal(sessionQueries,1);assert.equal(userQueries,1);
 await api.resolveSession({cookies:{...req.cookies}},'student');assert.equal(sessionQueries,2);
});
test('V60.7 students sharing a reverse proxy do not share an authenticated global rate-limit bucket',async()=>{
 const keys=[],limit=load('../src/middleware/rateLimit.js',{resolveSession:async req=>req.resolved,RateLimit:{findOneAndUpdate:f=>{keys.push(f._id);return query({count:1});}},privateKey:x=>x,emailValue:x=>x},'rateLimit')('global',600,60000,{sessionIdentity:true});
 for(const id of [uid,other])await limit({ip:'10.0.0.1',resolved:{portal:'student',user:{_id:id}}},response(),()=>{});
 assert.notEqual(keys[0],keys[1]);assert.match(keys[0],new RegExp(uid));assert.match(keys[1],new RegExp(other));
});
test('V60.7 version test derives current release while frozen certificate template is not rewritten',()=>{const source=fs.readFileSync(new URL('./v60-3-regressions.test.js',import.meta.url),'utf8');assert.match(source,/package\.json/);assert.doesNotMatch(source,/assert\.match\([^\n]+\/V60\\\.5\//);});
