/** Actual services against controlled model/HTTP doubles. No real payments. */
import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {load,query,response} from './testLoader.js';import * as business from '../src/utils/business.js';import * as security from '../src/utils/security.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return {resolve,reject,promise};};
function provider(fetcher){const timeouts=[],env={PAYPAL_CLIENT_ID:'fixture-client',PAYPAL_CLIENT_SECRET:'fixture-secret',PAYPAL_MODE:'sandbox'};const api=load('../src/services/paymentProviders.js',{crypto,...business,process:{env},fetch:fetcher,AbortSignal:{timeout:ms=>{timeouts.push(ms);return new AbortController().signal;}}},'({paypalApi})');return {...api,timeouts,env};}
test('PayPal starts the order timeout only after the OAuth response, not while waiting for it',async()=>{const d=deferred(),calls=[];const f=provider(async(url,opts)=>{calls.push({url,opts});if(url.endsWith('/token'))return d.promise;return Response.json({id:'TEST-ONLY'});});const p=f.paypalApi('/v2/checkout/orders',{method:'POST',requestId:'stable-test-id',body:{intent:'CAPTURE'}});await Promise.resolve();assert.deepEqual(f.timeouts,[10000]);assert.equal(calls.length,1);d.resolve(Response.json({access_token:'TEST_TOKEN',expires_in:3600}));assert.equal((await p).id,'TEST-ONLY');assert.deepEqual(f.timeouts,[10000,12000]);assert.equal(calls[1].opts.headers['PayPal-Request-Id'],'stable-test-id');});
test('simultaneous PayPal operations share one pending OAuth request without sharing order data',async()=>{const d=deferred(),paths=[];const f=provider(async url=>{paths.push(url);return url.endsWith('/token')?d.promise:Response.json({id:url.split('/').at(-1)});});const one=f.paypalApi('/v2/checkout/orders/ONE'),two=f.paypalApi('/v2/checkout/orders/TWO');await Promise.resolve();assert.equal(paths.length,1);d.resolve(Response.json({access_token:'TEST_TOKEN',expires_in:3600}));assert.deepEqual((await Promise.all([one,two])).map(x=>x.id),['ONE','TWO']);assert.equal(paths.filter(x=>x.endsWith('/token')).length,1);});
test('failed OAuth flight is cleared so a later explicit retry can authenticate',async()=>{let tokens=0;const f=provider(async url=>{if(url.endsWith('/token')){if(++tokens===1)return Response.json({error:'bad_gateway'},{status:502});return Response.json({access_token:'TEST_TOKEN',expires_in:3600});}return Response.json({ok:true});});await assert.rejects(()=>f.paypalApi('/v2/checkout/orders/ONE'),{status:502});assert.equal((await f.paypalApi('/v2/checkout/orders/ONE')).ok,true);assert.equal(tokens,2);});
test('PayPal credential/mode change never reuses the old OAuth token',async()=>{const authorization=[];let tokens=0;const f=provider(async(url,opts)=>{if(url.endsWith('/token'))return Response.json({access_token:'TOKEN_'+(++tokens),expires_in:3600});authorization.push(opts.headers.Authorization);return Response.json({ok:true});});await f.paypalApi('/v2/checkout/orders/ONE');f.env.PAYPAL_CLIENT_SECRET='changed-fixture-secret';await f.paypalApi('/v2/checkout/orders/TWO');f.env.PAYPAL_MODE='live';await f.paypalApi('/v2/checkout/orders/THREE');assert.equal(tokens,3);assert.deepEqual(authorization,['Bearer TOKEN_1','Bearer TOKEN_2','Bearer TOKEN_3']);});

function statusFixture(order){const filters=[],writes=[];const Model={findOne:filter=>{filters.push(filter);return query(order?.user===filter.user&&order?.requestKey===filter.requestKey?order:null);},create:()=>writes.push('create'),updateOne:()=>writes.push('update')};const api=load('../src/services/onlineCheckout.js',{crypto,...business,CheckoutOrder:Model},'({checkoutStatus})');return {...api,filters,writes};}
const key='fixture-checkout-12345',user='111111111111111111111111',hash=crypto.createHash('sha256').update(user+':'+key).digest('hex');
const request=(id=user)=>({user:{_id:id},headers:{'idempotency-key':key},get:()=>key});
const order={_id:'222222222222222222222222',user,requestKey:hash,provider:'stripe',environment:'test',providerOrderId:'cs_test_notreal',kind:'course',product:'test',status:'pending',approvalUrl:'https://checkout.stripe.com/c/pay/test-fixture',requestFingerprint:'HIDDEN'};
test('lost-checkout status reads only the current owner/key and never creates or captures money',async()=>{const f=statusFixture(order),out=await f.checkoutStatus(request());assert.equal(out.found,true);assert.equal(out.url,order.approvalUrl);assert.equal(f.filters[0].user,user);assert.equal(f.filters[0].requestKey,hash);assert.equal(JSON.stringify(out).includes('HIDDEN'),false);assert.equal('requestKey' in out.order,false);assert.equal(f.writes.length,0);});
test('another student cannot recover a checkout even with an identical browser request key',async()=>{const f=statusFixture(order),out=await f.checkoutStatus(request('333333333333333333333333'));assert.equal(out.found,false);assert.equal(out.url,null);assert.equal(out.order,null);assert.equal(f.writes.length,0);});
for(const status of ['paid','failed','cancelled','expired'])test('checkout recovery does not reuse an approval URL for '+status,async()=>{const f=statusFixture({...order,status}),out=await f.checkoutStatus(request());assert.equal(out.order.status,status);assert.equal(out.url,null);assert.equal(f.writes.length,0);});
test('unfinished remote creation is reported without starting a competing remote order',async()=>{const f=statusFixture({...order,status:'creating',providerOrderId:undefined,approvalUrl:undefined,creationClaimUntil:new Date(Date.now()+30000)});const out=await f.checkoutStatus(request());assert.equal(out.creationPending,true);assert.equal(out.url,null);assert.equal(f.writes.length,0);});
test('invalid idempotency key is rejected before checkout recovery query',async()=>{const f=statusFixture(order);await assert.rejects(()=>f.checkoutStatus({user:{_id:user},headers:{},get:()=>undefined}),{status:400});assert.equal(f.filters.length,0);});

test('server logout denial marker blocks API session resolution before DB reads',async()=>{let reads=0;const api=load('../src/middleware/auth.js',{...security,AuthSession:{findOne:()=>{reads++;return query(null);}}},'({resolveSession})');const result=await api.resolveSession({cookies:{sa_student_v45:'b'.repeat(64),sa_logout_student:'1'},headers:{'x-sa-portal':'student'}});assert.equal(result,null);assert.equal(reads,0);});
test('successful logout sets an explicit non-authentication denial cookie on root path',async()=>{const api=load('../src/controllers/authController.js',{...security,AuthSession:{updateMany:async()=>({})}},'({logout})'),res=response();await api.logout({cookies:{},headers:{'x-sa-portal':'student'}},res);const c=res.cookies.find(([name])=>name==='sa_logout_student');assert.ok(c);assert.equal(c[1],'1');assert.equal(c[2].path,'/');assert.equal(c[2].httpOnly,undefined);assert.equal(res.body.signedOut,true);});
