import test from 'node:test';import assert from 'node:assert/strict';
import * as security from '../src/utils/security.js';import {load,response,query} from './testLoader.js';
const a='a'.repeat(64),b='b'.repeat(64),c='c'.repeat(64);
function fixture(){
 const sessions=[{_id:'one',user:'A',portal:'student',tokenHash:security.hashToken(a),revokedAt:null},{_id:'two',user:'A',portal:'student',tokenHash:security.hashToken(b),revokedAt:null},{_id:'three',user:'staff',portal:'client_admin',tokenHash:security.hashToken(c),revokedAt:null}];
 const updates=[];const AuthSession={updateMany:async(filter,update)=>{updates.push(filter);for(const s of sessions)if(s.portal===filter.portal&&filter.tokenHash.$in.includes(s.tokenHash)&&s.revokedAt===null)Object.assign(s,update.$set);return {acknowledged:true};},findOne:filter=>query(sessions.find(s=>s.tokenHash===filter.tokenHash&&s.portal===filter.portal&&s.revokedAt===null)||null)};
 const {logout}=load('../src/controllers/authController.js',{...security,AuthSession},'({logout})');
 const {resolveSession}=load('../src/middleware/auth.js',{...security,AuthSession,User:{findById:()=>query(null)}},'({resolveSession})');
 return {logout,resolveSession,sessions,updates};
}
test('logout revokes both same-name cookie tokens and clears current plus legacy paths',async()=>{const f=fixture(),res=response();await f.logout({headers:{'x-sa-portal':'student',cookie:`sa_student_v45=${a}; sa_student_v45=${b}; sa_client_admin_v45=${c}`},cookies:{sa_student_v45:a}},res);assert.equal(res.body.signedOut,true);assert.ok(f.sessions[0].revokedAt);assert.ok(f.sessions[1].revokedAt);assert.equal(f.sessions[2].revokedAt,null);assert.equal(f.updates[0].portal,'student');assert.deepEqual(res.cleared.filter(([name])=>name===security.COOKIE_NAMES.student).map(([,opts])=>opts.path),['/api','/','/api/','/api/auth']);for(const [,options] of res.cleared)assert.equal('maxAge' in options,false);for(const token of [a,b])assert.equal(await f.resolveSession({headers:{'x-sa-portal':'student'},cookies:{sa_student_v45:token}}),null);});
test('logout with no session is idempotent and still expires the cookie paths',async()=>{const f=fixture(),res=response();await f.logout({cookies:{},headers:{}},res);assert.equal(res.body.success,true);assert.equal(f.updates.length,0);assert.equal(res.cleared.length,5);});
test('logout never sends malformed raw cookie values into the session query',async()=>{const f=fixture(),res=response();await f.logout({headers:{cookie:'sa_student_v45=%E0%A4%A; sa_student_v45={"$ne":null}'},cookies:{}},res);assert.equal(f.updates.length,0);assert.equal(res.body.success,true);});
test('failed database revocation cannot be reported as a successful server logout',async()=>{const {logout}=load('../src/controllers/authController.js',{...security,AuthSession:{updateMany:async()=>{throw new Error('Database unavailable');}}},'({logout})'),res=response();await assert.rejects(()=>logout({headers:{},cookies:{sa_student_v45:a}},res),/Database unavailable/);assert.equal(res.body,undefined);});
test('unknown portal logout returns validation error rather than success',async()=>{const f=fixture(),res=response();await f.logout({headers:{'x-sa-portal':'fake'},cookies:{}},res);assert.equal(res.code,400);assert.equal(f.updates.length,0);});
