import test from 'node:test';import assert from 'node:assert/strict';import {compileModule,browserGlobals} from './compile.mjs';
const json=(data,status=200,headers={})=>Response.json(data,{status,headers});
function fixture(fetcher){const b=browserGlobals(),events=[];b.window.addEventListener('sa:session-check',e=>events.push(e.detail));const boundary=compileModule('../lib/authBoundary.ts',{globals:b});return {api:compileModule('../lib/api.ts',{imports:{'./authBoundary':boundary},globals:{...b,fetch:fetcher}}),boundary,...b,events};}
test('API defaults to same-origin /api instead of a visitor localhost',()=>assert.equal(fixture(()=>{}).api.API_URL,'/api'));
test('transient GET failure retries once without expiring session',async()=>{let n=0;const f=fixture(async()=>++n===1?json({success:false},503):json({success:true,user:{id:'A'}}));assert.equal((await f.api.apiFetch('/content/team')).user.id,'A');assert.equal(n,2);assert.equal(f.events.length,0);});
test('long Retry-After is respected without hammering the backend',async()=>{let n=0;const f=fixture(async()=>{n++;return json({success:false,message:'Wait'},429,{'Retry-After':'45'});});await assert.rejects(()=>f.api.apiFetch('/auth/session'),{status:429});assert.equal(n,1);assert.equal(f.events.length,0);});
test('only recognized SESSION_REQUIRED requests a session recheck',async()=>{const f=fixture(async()=>json({success:false,code:'SESSION_REQUIRED'},401));await assert.rejects(()=>f.api.apiFetch('/courses/x/learn'),{status:401});assert.equal(f.events.length,1);assert.equal(f.events[0].portal,'student');});
test('provider/password 401 does not clear the student session',async()=>{const f=fixture(async()=>json({success:false,code:'PROVIDER_UNAUTHORIZED'},401));await assert.rejects(()=>f.api.apiFetch('/payments/orders/x/confirm',{method:'POST'}),{status:401});assert.equal(f.events.length,0);});
test('mutating checkout is never automatically retried',async()=>{let n=0;const f=fixture(async(url,opts)=>{n++;assert.equal(opts.headers.get('Idempotency-Key'),'same-key');return json({success:false},503);});await assert.rejects(()=>f.api.apiFetch('/payments/checkout',{method:'POST',headers:{'Idempotency-Key':'same-key'},body:'{}'}),{status:503});assert.equal(n,1);});
test('shared public request survives one subscriber abort',async()=>{let done,n=0;const f=fixture(()=>{n++;return new Promise(r=>done=r);}),c=new AbortController();const a=f.api.apiFetch('/content/team',{signal:c.signal}),b=f.api.apiFetch('/content/team');c.abort();await assert.rejects(()=>a,{name:'AbortError'});done(json({success:true,team:[{name:'Founder'}]}));assert.equal((await b).team[0].name,'Founder');assert.equal(n,1);});
test('only public data is reused; private progress is read per request',async()=>{let n=0;const f=fixture(async()=>{n++;return json({success:true,courses:[]});});await f.api.apiFetch('/courses');await f.api.apiFetch('/courses');assert.equal(n,1);await f.api.apiFetch('/courses/enrolled/mine');await f.api.apiFetch('/courses/enrolled/mine');assert.equal(n,3);});
test('caller cancellation remains AbortError, not a fabricated timeout',async()=>{const f=fixture(async()=>json({success:true})),c=new AbortController();c.abort();await assert.rejects(()=>f.api.apiFetch('/auth/session',{signal:c.signal}),{name:'AbortError'});});
test('stale 401 from before a new login cannot invalidate that account',async()=>{let fail;const f=fixture(async url=>url.endsWith('/auth/login')?json({success:true,user:{id:'B',role:'student'}}):new Promise(r=>fail=r));const old=f.api.apiFetch('/courses/x/learn');await f.api.apiFetch('/auth/login',{method:'POST'});fail(json({success:false,code:'SESSION_REQUIRED'},401));await assert.rejects(()=>old);assert.equal(f.events.length,0);});
test('login-only catalog and private requests both include HttpOnly cookies',async()=>{const seen=[];const f=fixture(async(u,o)=>{seen.push(o.credentials);return json({success:true});});await f.api.apiFetch('/content/team');await f.api.apiFetch('/auth/session');assert.deepEqual(seen,['include','include']);});
test('invalid upstream HTML is not converted into empty JSON success',async()=>{let n=0;const f=fixture(async()=>{n++;return new Response('<html>503</html>',{status:503});});await assert.rejects(()=>f.api.apiFetch('/content/team'),{status:503,code:'API_INVALID_RESPONSE'});assert.equal(n,2);assert.equal(f.api.publicApiSnapshot('/content/team'),undefined);});

test('successful logout fences cached session replies across reloads until credentials login',async()=>{let calls=0;const f=fixture(async url=>{calls++;return json(url.endsWith('/auth/logout')?{success:true,signedOut:true}:{success:true,user:{id:'B',role:'student'}});});await f.api.apiFetch('/auth/logout',{method:'POST'});assert.equal(f.boundary.explicitlyLoggedOut('student'),true);const before=calls;assert.equal((await f.api.apiFetch('/auth/session')).user,null);assert.equal(calls,before);await f.api.apiFetch('/auth/login',{method:'POST'});assert.equal(f.boundary.explicitlyLoggedOut('student'),false);assert.equal((await f.api.apiFetch('/auth/session')).user.id,'B');});
test('late successful private response from before logout cannot expose old billing',async()=>{let resolve;const f=fixture(async url=>url.endsWith('/auth/logout')?json({success:true,signedOut:true}):new Promise(r=>resolve=r));const old=f.api.apiFetch('/payments/mine/invoices');await f.api.apiFetch('/auth/logout',{method:'POST'});resolve(json({success:true,items:[{user:'A'}]}));await assert.rejects(()=>old,{name:'AbortError'});});
test('logout waits for an older credentials Set-Cookie before revoking it and never delivers the stale user',async()=>{let resolve;const calls=[];const f=fixture(async url=>{calls.push(url);return url.endsWith('/auth/logout')?json({success:true,signedOut:true}):new Promise(r=>resolve=r);});const old=f.api.apiFetch('/auth/login',{method:'POST'});const rejected=assert.rejects(()=>old,{name:'AbortError'});const out=f.api.apiFetch('/auth/logout',{method:'POST'});assert.equal(f.boundary.explicitlyLoggedOut('student'),true);assert.equal(calls.length,1);resolve(json({success:true,user:{id:'A',role:'student'}}));await rejected;await out;assert.deepEqual(calls,['/api/auth/login','/api/auth/logout']);assert.equal(f.boundary.explicitlyLoggedOut('student'),true);});
test('logout fence does not hide public reviews or public payment methods',async()=>{const f=fixture(async()=>json({success:true,items:[]}));await f.api.apiFetch('/auth/logout',{method:'POST'});await f.api.apiFetch('/reviews');await f.api.apiFetch('/payments/methods');await assert.rejects(()=>f.api.apiFetch('/payments/mine/invoices'),{status:401});});
test('failed explicit logout does not restore browser identity and can be retried',async()=>{let n=0;const f=fixture(async()=>++n===1?json({success:false},503):json({success:true,signedOut:true}));await assert.rejects(()=>f.api.apiFetch('/auth/logout',{method:'POST'}),{status:503});assert.equal(f.boundary.explicitlyLoggedOut('student'),true);assert.equal((await f.api.apiFetch('/auth/session')).user,null);await f.api.apiFetch('/auth/logout',{method:'POST'});assert.equal(n,2);});

test('explicit new login waits for pending logout cookie expiration before it sends credentials',async()=>{let finish;const calls=[];const f=fixture(async url=>{calls.push(url);return url.endsWith('/auth/logout')?new Promise(r=>finish=r):json({success:true,user:{id:'B',role:'student'}});});const out=f.api.apiFetch('/auth/logout',{method:'POST'});const login=f.api.apiFetch('/auth/login',{method:'POST'});await Promise.resolve();assert.equal(calls.length,1);finish(json({success:true,signedOut:true}));await out;await login;assert.equal(calls.length,2);assert.equal(f.boundary.explicitlyLoggedOut('student'),false);});
test('simultaneous logout clicks share a single revocation request',async()=>{let finish,n=0;const f=fixture(()=>{n++;return new Promise(r=>finish=r);});const a=f.api.apiFetch('/auth/logout',{method:'POST'}),b=f.api.apiFetch('/auth/logout',{method:'POST'});finish(json({success:true,signedOut:true}));await Promise.all([a,b]);assert.equal(n,1);});

test('catalog memoization is portal-specific even with an explicit portal header',async()=>{let reads=0;const f=fixture(async(u,o)=>{reads++;return json({success:true,portal:o.headers.get('X-SA-Portal'),courses:[]});});const a=await f.api.apiFetch('/courses'),b=await f.api.apiFetch('/courses',{headers:{'X-SA-Portal':'client_admin'}});assert.equal(a.portal,'student');assert.equal(b.portal,'client_admin');assert.equal(reads,2);});
test('logout drops the catalog snapshot instead of exposing cached content after sign-out',async()=>{const f=fixture(async url=>json(url.endsWith('/auth/logout')?{success:true,signedOut:true}:{success:true,team:[{name:'Member'}]}));await f.api.apiFetch('/content/team');assert.ok(f.api.publicApiSnapshot('/content/team'));await f.api.apiFetch('/auth/logout',{method:'POST'});assert.equal(f.api.publicApiSnapshot('/content/team'),undefined);});
test('late catalog response from before logout cannot repopulate a new session cache',async()=>{let done;const f=fixture(async url=>url.endsWith('/auth/logout')?json({success:true,signedOut:true}):new Promise(r=>done=r));const old=f.api.apiFetch('/content/team');await f.api.apiFetch('/auth/logout',{method:'POST'});done(json({success:true,team:[{name:'Old'}]}));await assert.rejects(()=>old,{name:'AbortError'});assert.equal(f.api.publicApiSnapshot('/content/team'),undefined);});

for(const body of [{success:true},{success:true,user:{id:'student-a'}},{success:true,user:{id:'admin-a',role:'client_admin'}},{success:true,user:{role:'student'}},{user:{id:'student-a',role:'student'}}])test('invalid login response cannot clear explicit logout fence: '+JSON.stringify(body),async()=>{const f=fixture(async()=>json(body));f.boundary.markExplicitLogout('student');await assert.rejects(()=>f.api.apiFetch('/auth/login',{method:'POST'}),{code:'AUTH_RESPONSE_INVALID'});assert.equal(f.boundary.explicitlyLoggedOut('student'),true);});
