/** Actual AuthProvider hook callbacks evaluated in a deterministic hook harness.
 * This is a unit/state-machine test, not a claim of a running Next.js browser build. */
import test from 'node:test';import assert from 'node:assert/strict';
import {compileModule,browserGlobals} from './compile.mjs';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
class ApiError extends Error{constructor(message,status,code){super(message);Object.assign(this,{status,code});}}
function fixture({fetchSession,pathname='/courses',initialSession=null}={}){
 const browser=browserGlobals(),slots=[],pendingEffects=[],timers=new Map(),epochs={student:0,client_admin:0,super_admin:0};
 const destinations=[];browser.window.location.replace=path=>destinations.push(path);
 let customFetcher=false;
 const boundary=compileModule('../lib/authBoundary.ts',{globals:browser});
 let cursor=0,tree,rendering=false,scheduled=false,mounted=true,timer=0,route=pathname,api,fetcher=fetchSession||(()=>Promise.resolve({success:true,user:null})),calls=[];
 const same=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
 const schedule=()=>{if(!mounted||scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;if(mounted)render();});};
 const React={Fragment:'Fragment',createContext:()=>({Provider:'Provider'}),useContext:()=>null,
  useState(value){const i=cursor++;if(!slots[i])slots[i]={value:typeof value==='function'?value():value};return [slots[i].value,next=>{const value=typeof next==='function'?next(slots[i].value):next;if(!Object.is(value,slots[i].value)){slots[i].value=value;schedule();}}];},
  useRef(value){const i=cursor++;if(!slots[i])slots[i]={current:value};return slots[i];},
  useMemo(fn,deps){const i=cursor++;if(!slots[i]||!same(slots[i].deps,deps))slots[i]={deps,value:fn()};return slots[i].value;},
  useCallback(fn,deps){return React.useMemo(()=>fn,deps);},
  useEffect(fn,deps){const i=cursor++;if(!slots[i]||!same(slots[i].deps,deps)){const previous=slots[i]?.cleanup;slots[i]={deps};pendingEffects.push(()=>{previous?.();slots[i].cleanup=fn();});}}
 };
 const jsx=(type,props,key)=>({type,props,key});
 const module=compileModule('../components/auth/AuthProvider.tsx',{imports:{react:React,'react/jsx-runtime':{jsx,jsxs:jsx},'next/navigation':{usePathname:()=>route},'../../lib/api':{
  apiFetch:(path,options)=>{calls.push({path,options});return path==='/auth/logout'&&!customFetcher?Promise.resolve({success:true,signedOut:true,portal:options.headers['X-SA-Portal']}):fetcher(path,options);},ApiError,isAbortError:e=>e?.name==='AbortError',portalForPath:p=>p.startsWith('/super-admin')?'super_admin':p.startsWith('/admin')?'client_admin':'student',accountEpoch:p=>epochs[p],invalidateAccountRequests:p=>epochs[p]++,beginExplicitLogout:p=>{epochs[p]++;return boundary.markExplicitLogout(p);},boundaryMarker:boundary.boundaryMarker,explicitlyLoggedOut:boundary.explicitlyLoggedOut
 },'../../lib/useHydrated':{useHydrated:()=>true},'../../lib/authBoundary':boundary},globals:{...browser,setInterval:fn=>{timers.set(++timer,fn);return timer;},clearInterval:id=>timers.delete(id),setTimeout:fn=>{timers.set(++timer,fn);return timer;},clearTimeout:id=>timers.delete(id)}});
 function render(){if(rendering)throw Error('Recursive render');rendering=true;cursor=0;tree=module.AuthProvider({children:'app',initialSession});rendering=false;while(pendingEffects.length)pendingEffects.shift()();}
 render();
 return {calls,browser,boundary,destinations,epoch:portal=>epochs[portal],async settle(){for(let i=0;i<15;i++)await Promise.resolve();},get value(){return tree.props.value;},get tree(){return tree;},setFetcher(fn){customFetcher=true;fetcher=fn;},async route(path){route=path;render();await this.settle();},authenticate(user,portal='student'){epochs[portal]++;boundary.markExplicitLogin(portal);browser.window.dispatchEvent(new CustomEvent('sa:authenticated',{detail:{portal,user}}));},cleanup(){mounted=false;for(const slot of slots)slot?.cleanup?.();timers.clear();}};
}
const learner={id:'student-a',role:'student',name:'Student A'};
test('verified student remains signed in after transient session 503',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const saved=f.value.user;f.setFetcher(()=>Promise.reject(new ApiError('Busy',503)));await f.value.refresh();await f.settle();assert.equal(f.value.user,saved);assert.equal(f.value.ready,true);assert.match(f.value.sessionError,/Connection/);});
test('initial session failure stays unresolved rather than redirecting as an anonymous user',async t=>{const f=fixture({fetchSession:()=>Promise.reject(new ApiError('Busy',503))});t.after(()=>f.cleanup());await f.settle();assert.equal(f.value.ready,false);assert.ok(f.value.sessionError);});
test('identical session refresh preserves user object identity and therefore learning draft dependencies',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:{...learner}})});t.after(()=>f.cleanup());await f.settle();const saved=f.value.user;await f.value.refresh();await f.settle();assert.equal(f.value.user,saved);});
test('confirmed anonymous session actually clears expired authentication',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();f.setFetcher(()=>Promise.resolve({user:null}));await f.value.refresh();await f.settle();assert.equal(f.value.user,null);assert.equal(f.value.ready,true);assert.equal(f.value.sessionError,'');});
test('old anonymous response cannot overwrite a later successful login',async t=>{const old=deferred(),f=fixture({fetchSession:()=>old.promise});t.after(()=>f.cleanup());f.authenticate(learner);await f.settle();old.resolve({user:null});await f.settle();assert.equal(f.value.user.id,'student-a');assert.equal(f.value.ready,true);});
test('failed explicit logout hides local identity and reports that server revocation needs retry',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();f.setFetcher(()=>Promise.reject(new ApiError('Busy',503)));await assert.rejects(()=>f.value.logout(),{status:503});await f.settle();assert.equal(f.value.user,null);assert.equal(f.boundary.explicitlyLoggedOut('student'),true);});
test('switching portals never reuses a student identity for client admin',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const admin=deferred();f.setFetcher(()=>admin.promise);await f.route('/admin');assert.equal(f.value.user,null);assert.equal(f.value.ready,false);assert.equal(f.value.portal,'client_admin');admin.resolve({user:{id:'admin-a',role:'client_admin'}});await f.settle();assert.equal(f.value.user.role,'client_admin');assert.equal(f.calls.at(-1).options.headers['X-SA-Portal'],'client_admin');});
test('changing accounts updates identity without remounting the whole root hydration tree',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();f.authenticate({...learner,id:'student-b'});await f.settle();assert.equal(f.value.user.id,'student-b');assert.equal(f.tree.props.children[1],'app');});
test('duplicate unauthorized notifications share one session revalidation',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const p=deferred(),before=f.calls.length;f.setFetcher(()=>p.promise);for(let i=0;i<4;i++)f.browser.window.dispatchEvent(new CustomEvent('sa:session-check',{detail:{portal:'student',epoch:f.epoch('student')}}));assert.equal(f.calls.length,before+1);p.resolve({user:{...learner}});await f.settle();assert.equal(f.value.user.id,learner.id);});

test('successful logout survives pageshow, focus and manual session refresh',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner,success:true})});t.after(()=>f.cleanup());await f.settle();await f.value.logout();await f.settle();const before=f.calls.length;const event=new Event('pageshow');Object.defineProperty(event,'persisted',{value:true});f.browser.window.dispatchEvent(event);f.browser.window.dispatchEvent(new Event('focus'));await f.value.refresh();await f.settle();assert.equal(f.value.user,null);assert.equal(f.value.ready,true);assert.equal(f.calls.length,before);});
test('old session GET finishing after logout cannot bring the student back',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const delayed=deferred();f.setFetcher(path=>path==='/auth/logout'?Promise.resolve({success:true,signedOut:true}):delayed.promise);const refresh=f.value.refresh();await f.value.logout();delayed.resolve({user:learner});await refresh;await f.settle();assert.equal(f.value.user,null);});
test('storage logout from another tab clears current account immediately',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();f.browser.window.localStorage.setItem(f.boundary.AUTH_BOUNDARY_PREFIX+'student','logout:other-tab');const event=new Event('storage');Object.defineProperty(event,'key',{value:f.boundary.AUTH_BOUNDARY_PREFIX+'student'});f.browser.window.dispatchEvent(event);await f.settle();assert.equal(f.value.user,null);});
test('actual explicit sign-in after logout restores the newly authenticated account',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({success:true,user:learner})});t.after(()=>f.cleanup());await f.settle();await f.value.logout();await f.settle();f.authenticate({...learner,id:'student-b'});await f.settle();assert.equal(f.value.user.id,'student-b');assert.equal(f.boundary.explicitlyLoggedOut('student'),false);});
test('student logout boundary does not sign out a separately authenticated admin',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();await f.value.logout();f.setFetcher(()=>Promise.resolve({user:{id:'admin-a',role:'client_admin'}}));await f.route('/admin');await f.settle();assert.equal(f.value.user.id,'admin-a');assert.equal(f.value.portal,'client_admin');});

test('late student logout response cannot replace a separately opened admin session',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const delayed=deferred();f.setFetcher(path=>path==='/auth/logout'?delayed.promise:Promise.resolve({user:{id:'admin-a',role:'client_admin'}}));const out=f.value.logout();await f.settle();await f.route('/admin');assert.equal(f.value.user.id,'admin-a');delayed.resolve({success:true,signedOut:true});await out;await f.settle();assert.equal(f.value.user.id,'admin-a');assert.equal(f.value.portal,'client_admin');});
test('logout success cannot clear a newer explicitly authenticated identity',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const delayed=deferred();f.setFetcher(()=>delayed.promise);const out=f.value.logout();await f.settle();f.authenticate({...learner,id:'student-b'});await f.settle();delayed.resolve({success:true,signedOut:true});await out;await f.settle();assert.equal(f.value.user.id,'student-b');});

test('server-verified page session bootstraps login without a duplicate initial request',async t=>{const f=fixture({initialSession:{portal:'student',user:learner,setupRequired:false},fetchSession:()=>{throw Error('unnecessary request');}});t.after(()=>f.cleanup());await f.settle();assert.equal(f.value.ready,true);assert.equal(f.value.user.id,learner.id);assert.equal(f.calls.length,0);});
test('verified bootstrap cannot resurrect identity after explicit logout',async t=>{const f=fixture({initialSession:{portal:'student',user:learner},fetchSession:()=>Promise.resolve({success:true,signedOut:true})});t.after(()=>f.cleanup());await f.settle();await f.value.logout();await f.settle();f.browser.window.dispatchEvent(new Event('focus'));await f.settle();assert.equal(f.value.user,null);assert.equal(f.boundary.explicitlyLoggedOut('student'),true);});

test('logout coordinates exactly one document replacement to the public landing',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();const one=f.value.logout(),two=f.value.logout();await Promise.all([one,two]);await f.settle();assert.deepEqual(f.destinations,['/']);assert.equal(f.calls.filter(c=>c.path==='/auth/logout').length,1);assert.equal(f.boundary.logoutNeedsRetry('student'),false);});
test('unconfirmed logout response preserves a retry marker and never restores stale identity',async t=>{const f=fixture({fetchSession:()=>Promise.resolve({user:learner})});t.after(()=>f.cleanup());await f.settle();f.setFetcher(()=>Promise.resolve({success:true,user:learner}));await assert.rejects(()=>f.value.logout(),{code:'LOGOUT_UNCONFIRMED'});await f.settle();assert.equal(f.value.user,null);assert.equal(f.boundary.logoutNeedsRetry('student'),true);assert.deepEqual(f.destinations,['/']);});
