import test from 'node:test';import assert from 'node:assert/strict';
import {compileModule,browserGlobals} from './compile.mjs';import {hookHarness} from './hooks.mjs';
function fixture({cached,load=async()=>({courses:[]})}={}){
 const h=hookHarness(),b=browserGlobals(),navigator={onLine:true};let reads=0,invalidations=0;
 const mod=compileModule('../lib/usePublicResource.ts',{imports:{react:h.React,'./api':{apiFetch:(...args)=>{reads++;return load(...args);},isAbortError:e=>e?.name==='AbortError',invalidatePublicApi:()=>invalidations++,publicApiSnapshot:()=>cached}},globals:{...h.globals,...b,navigator}});
 h.mount(()=>mod.usePublicResource('/courses','courses'));return {h,b,navigator,get reads(){return reads;},get invalidations(){return invalidations;}};
}
test('catalog hydration is deterministic then reuses known cached empty data before network completes',async()=>{let finish;const f=fixture({cached:{courses:[]},load:()=>new Promise(r=>finish=r)});assert.equal(f.h.tree.loading,true);assert.equal(f.h.tree.loaded,false);await f.h.settle();assert.equal(f.h.tree.loading,false);assert.equal(f.h.tree.loaded,true);finish({courses:[]});await f.h.settle();assert.equal(f.h.tree.loading,false);f.h.cleanup();});
test('transient catalog refresh failure keeps real previous courses visible',async()=>{let calls=0;const f=fixture({load:async()=>{if(++calls===1)return {courses:[{slug:'real'}]};throw Error('network unavailable');}});await f.h.settle();f.h.run(30000);await f.h.settle();assert.equal(f.h.tree.data[0].slug,'real');assert.match(f.h.tree.error,/network/);assert.equal(f.h.tree.loading,false);f.h.cleanup();});
test('catalog background refresh pauses while hidden and offline',async()=>{const f=fixture();await f.h.settle();assert.equal(f.reads,1);f.b.document.visibilityState='hidden';f.h.run(30000);await f.h.settle();assert.equal(f.reads,1);f.b.document.visibilityState='visible';f.navigator.onLine=false;f.h.run(30000);await f.h.settle();assert.equal(f.reads,1);f.navigator.onLine=true;f.b.window.dispatchEvent(new Event('online'));await f.h.settle();assert.equal(f.reads,2);f.h.cleanup();});
test('malformed team/catalog response is an error, not a successful empty library',async()=>{const f=fixture({load:async()=>({success:true})});await f.h.settle();assert.equal(f.h.tree.loaded,false);assert.match(f.h.tree.error,/incomplete/);f.h.cleanup();});
test('manual retry invalidates only catalog reuse then re-reads',async()=>{const f=fixture();await f.h.settle();f.h.tree.retry();await f.h.settle();assert.equal(f.invalidations,1);assert.equal(f.reads,2);f.h.cleanup();});
