import test from 'node:test';import assert from 'node:assert/strict';import {compileModule} from './compile.mjs';
const {createCompletionFeed}=compileModule('../lib/completionFeed.ts');
const A='a'.repeat(24),B='b'.repeat(24),pending={_id:A,status:'pending',courseTitle:'Course A'},issued={...pending,status:'issued',certificateNumber:'SA-DEMO'};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {resolve,reject,promise};};
function fixture(load){const timers=new Map();let n=0,visible=true;const feed=createCompletionFeed({load,visible:()=>visible,schedule:(fn,ms)=>{timers.set(++n,{fn,ms});return n;},cancel:id=>timers.delete(id)});return {feed,timers,hide(){visible=false;feed.wake();},show(){visible=true;feed.wake();},delay(){return [...timers.values()].at(-1)?.ms;}};}
test('pending certificate becomes downloadable status without reloading course/progress',async()=>{const calls=[],updates=[];const f=fixture(async(ids)=>{calls.push([...ids]);return [issued];});const stop=f.feed.subscribe(A,pending,(item,error)=>updates.push({item,error}));await f.feed.tick();assert.equal(updates.at(-1).item.status,'issued');assert.deepEqual(calls,[[A]]);assert.equal(f.delay(),15000);stop();assert.equal(f.timers.size,0);});
test('all views of the same certificate share one request and notify both subscribers',async()=>{let calls=0;const a=[],b=[];const f=fixture(async()=>{calls++;return [issued];});f.feed.subscribe(A,pending,item=>a.push(item));f.feed.subscribe(A,pending,item=>b.push(item));await f.feed.tick();assert.equal(calls,1);assert.equal(a.at(-1).status,'issued');assert.equal(b.at(-1).status,'issued');f.feed.dispose();});
test('pending interval is bounded at 3 seconds, no immediate recursive polling',async()=>{const f=fixture(async()=>[pending]);f.feed.subscribe(A,pending,()=>{});await f.feed.tick();assert.equal(f.delay(),3000);assert.equal(f.timers.size,1);f.feed.dispose();});
test('identical status does not trigger redundant component rendering',async()=>{let count=0;const f=fixture(async()=>[{...pending}]);f.feed.subscribe(A,pending,()=>count++);await f.feed.tick();await f.feed.tick();assert.equal(count,1);f.feed.dispose();});
test('hidden/offline document does not poll and visibility wake resumes',async()=>{let reads=0;const f=fixture(async()=>{reads++;return [pending];});f.feed.subscribe(A,pending,()=>{});f.hide();await f.feed.tick();assert.equal(reads,0);assert.equal(f.timers.size,0);f.show();assert.equal(f.delay(),0);await f.feed.tick();assert.equal(reads,1);f.feed.dispose();});
test('in-flight requests never overlap during focus storms',async()=>{const p=deferred();let reads=0;const f=fixture(async()=>{reads++;return p.promise;});f.feed.subscribe(A,pending,()=>{});const task=f.feed.tick();for(let i=0;i<8;i++){f.feed.wake();await f.feed.tick();}assert.equal(reads,1);p.resolve([pending]);await task;f.feed.dispose();});
test('last unmount cancels work and late status cannot update another account',async()=>{const p=deferred();let signal;const updates=[];const f=fixture(async(ids,s)=>{signal=s;return p.promise;});const stop=f.feed.subscribe(A,pending,item=>updates.push(item));const task=f.feed.tick();stop();assert.equal(signal.aborted,true);p.resolve([issued]);await task;assert.equal(updates.length,1);assert.equal(f.feed.size,0);assert.equal(f.timers.size,0);});
test('unrequested certificate IDs from a malformed response are never merged',async()=>{const seen=[];const f=fixture(async()=>[{_id:B,status:'issued'}]);f.feed.subscribe(A,pending,item=>seen.push(item));await f.feed.tick();assert.equal(seen.length,1);f.feed.dispose();});
test('temporary failure preserves pending record and backs off',async()=>{const updates=[];const f=fixture(async()=>{throw Error('busy');});f.feed.subscribe(A,pending,(item,error)=>updates.push({item,error}));await f.feed.tick();assert.equal(updates.at(-1).item.status,'pending');assert.match(updates.at(-1).error,/Retrying/);assert.equal(f.delay(),6000);await f.feed.tick();assert.equal(f.delay(),12000);for(let i=0;i<4;i++)await f.feed.tick();assert.equal(f.delay(),30000);f.feed.dispose();});
test('status feeds batch at most 100 IDs per backend read',async()=>{const batches=[];const f=fixture(async ids=>{batches.push(ids.length);return [];});for(let i=1;i<=205;i++){const id=i.toString(16).padStart(24,'0');f.feed.subscribe(id,{_id:id,status:'issued'},()=>{});}await f.feed.tick();assert.deepEqual(batches,[100,100,5]);f.feed.dispose();});
test('new student watcher does not reuse previous students certificate status',async()=>{const one=fixture(async()=>[issued]);one.feed.subscribe(A,pending,()=>{});await one.feed.tick();one.feed.dispose();const updates=[],two=fixture(async()=>[{_id:B,status:'pending'}]);two.feed.subscribe(B,{_id:B,status:'pending'},item=>updates.push(item));await two.feed.tick();assert.equal(updates.some(item=>item._id===A),false);two.feed.dispose();});
