/** Real policy/middleware functions with a controlled backend; no identity is inferred from a cookie alone. */
import test from 'node:test';import assert from 'node:assert/strict';
import {compileModule} from './compile.mjs';import {proxyTarget} from '../lib/server/apiProxy.mjs';
const policy=compileModule('../lib/pagePolicy.ts');
const env={NODE_ENV:'development',API_PROXY_TARGET:'http://127.0.0.1:5000'};
const module=compileModule('../lib/server/pageSession.ts',{imports:{'../pagePolicy':policy,'./apiProxy.mjs':{proxyTarget}}});
const token='a'.repeat(64),url='http://localhost:3000',cookies={student:'sa_student_v45',client_admin:'sa_client_admin_v45',super_admin:'sa_super_admin_v45'};
const request=(path,cookie='',extra={})=>new Request(url+path,{headers:{cookie,...extra}});
const user=role=>({id:role+'-id',role,name:'Learner',email:'learner@example.invalid'});
for(const path of ['/home','/about','/courses','/courses/test','/team','/events','/contact','/academy','/reviews','/learn/test','/my-course','/billing','/certificates','/checkout/return?order=abc'])test('direct guest page redirects without exposing content: '+path,async()=>{let reads=0;const r=await module.pageSession(request(path),env,async()=>{reads++;throw Error();});const p=new URL(r.redirect,url);assert.equal(p.pathname,'/login');assert.equal(p.searchParams.get('next'),path);assert.equal(reads,0);});
for(const path of ['/','/connection?next=%2Fabout','/login','/register','/forgot-password','/reset-password?token=private','/terms','/privacy','/admin/login','/super-admin/login','/certificates/verify/'+'a'.repeat(48)])test('necessary open route does not require a session: '+path,async()=>{const r=await module.pageSession(request(path),env,async()=>{throw Error('must not fetch');});assert.equal(r.redirect,undefined);assert.equal(r.unavailable,undefined);if(r.session){assert.equal(r.session.user,null);assert.equal(r.session.verified,true);}else assert.equal(Object.keys(r).length,0);});
for(const [path,role] of [['/about','student'],['/admin','client_admin'],['/super-admin','super_admin']])test('validated same-role session bootstraps '+role,async()=>{let reads=0;const r=await module.pageSession(request(path,cookies[role]+'='+token),env,async(target,opts)=>{reads++;assert.equal(target,env.API_PROXY_TARGET+'/api/auth/session?compact=1');assert.equal(opts.headers.get('X-SA-Portal'),role);assert.equal(opts.cache,'no-store');assert.equal(opts.redirect,'manual');return Response.json({success:true,user:{...user(role),passwordHash:'DO-NOT-FORWARD',mfaSecret:'DO-NOT-FORWARD'},setupRequired:role!=='student'});});assert.equal(r.session.user.role,role);assert.equal(reads,1);assert.equal(JSON.stringify(r).includes('DO-NOT-FORWARD'),false);});
test('a student cookie never authenticates the admin portal',async()=>{const r=await module.pageSession(request('/admin',cookies.student+'='+token),env,async()=>{throw Error();});assert.ok(r.redirect.startsWith('/admin/login?'));});
test('forged cookie without a valid DB session cannot open About',async()=>{const r=await module.pageSession(request('/about',cookies.student+'='+token),env,async()=>Response.json({success:true,user:null}));assert.ok(r.redirect.startsWith('/login?'));});
test('client logout fence blocks document navigation even when an old cookie remains',async()=>{let reads=0;const r=await module.pageSession(request('/about',cookies.student+'='+token+'; sa_logout_student=1'),env,async()=>{reads++;return Response.json({success:true,user:user('student')});});assert.ok(r.redirect);assert.equal(reads,0);});
for(const data of [{success:true,user:user('super_admin')},{success:true,user:null}])test('wrong-role or expired backend session redirects safely: '+JSON.stringify(data),async()=>{const r=await module.pageSession(request('/about',cookies.student+'='+token),env,async()=>Response.json(data));assert.ok(r.redirect);});
for(const status of [500,502,503,504])test('page auth '+status+' is unavailable, not a fabricated logout',async()=>{const r=await module.pageSession(request('/about',cookies.student+'='+token),env,async()=>Response.json({success:false},{status}));assert.equal(r.unavailable,true);assert.equal(r.redirect,undefined);});
test('network failure fails closed without rendering protected page',async()=>{const r=await module.pageSession(request('/about',cookies.student+'='+token),env,async()=>{throw new TypeError('network');});assert.equal(r.unavailable,true);assert.equal(r.session,undefined);});
test('incomplete JSON is not an authenticated bootstrap',async()=>{const r=await module.pageSession(request('/about',cookies.student+'='+token),env,async()=>Response.json({success:true}));assert.equal(r.unavailable,true);});
function middlewareFixture(outcome){
 class NextResponse extends Response{static redirect(location){return new NextResponse(null,{status:307,headers:{location:String(location)}});}static next(options){const r=new NextResponse(null);r.forwarded=options.request.headers;return r;}}
 return compileModule('../middleware.ts',{imports:{'next/server':{NextResponse},'./lib/server/pageSession':{pageSession:async()=>outcome,SNAPSHOT_HEADER:module.SNAPSHOT_HEADER}},globals:{process:{env},btoa}}).middleware;
}
test('middleware strips a browser-supplied verified-session header even on public login',async()=>{const result=await middlewareFixture({})(request('/login','',{[module.SNAPSHOT_HEADER]:'attacker'}));assert.equal(result.forwarded.has(module.SNAPSHOT_HEADER),false);assert.match(result.headers.get('cache-control'),/no-store/);});
test('middleware forwards only newly verified safe account snapshot',async()=>{const session={portal:'student',user:user('student'),setupRequired:false};const result=await middlewareFixture({session})(request('/about','',{[module.SNAPSHOT_HEADER]:'attacker'}));assert.deepEqual(JSON.parse(decodeURIComponent(result.forwarded.get(module.SNAPSHOT_HEADER))),session);});
test('unavailable page middleware redirects to reconnect without logout or raw RSC HTML',async()=>{const result=await middlewareFixture({unavailable:true})(request('/about'));assert.equal(result.status,307);assert.equal(result.headers.get('set-cookie'),null);const location=new URL(result.headers.get('location'));assert.equal(location.pathname,'/connection');assert.equal(location.searchParams.get('next'),'/about');});
