import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';import {proxyApi,proxyTarget} from '../lib/server/apiProxy.mjs';
const env={NODE_ENV:'production',API_PROXY_TARGET:'https://api.academy.test'};
const req=(path,init={})=>new Request('https://academy.test'+path,init);
test('proxy refuses missing, self-referencing and non-origin upstream settings',()=>{for(const raw of ['', 'https://academy.test','https://user:pass@api.test','https://api.test/api','http://api.test'])assert.throws(()=>proxyTarget({...env,API_PROXY_TARGET:raw},'https://academy.test'));});
test('proxy resolves target at runtime and forbids upstream redirects',async()=>{let called;const res=await proxyApi(req('/api/health'),{env,fetcher:async url=>{called=url;return new Response(null,{status:302,headers:{Location:'https://somewhere.test'}});}});assert.equal(called,'https://api.academy.test/api/health');assert.equal(res.status,502);assert.equal((await res.json()).code,'API_REDIRECT');});
test('proxy forwards cookies and portal, discards client host/IP spoof headers',async()=>{await proxyApi(req('/api/auth/session',{headers:{cookie:'sa_student_v45=abc','x-sa-portal':'student',host:'evil.test','x-forwarded-for':'1.2.3.4'}}),{env,fetcher:async(url,o)=>{assert.equal(o.headers.get('cookie'),'sa_student_v45=abc');assert.equal(o.headers.get('x-sa-portal'),'student');assert.equal(o.headers.get('host'),null);assert.equal(o.headers.get('x-forwarded-for'),null);return Response.json({success:true});}});});
test('proxy preserves separate Set-Cookie headers, makes Academy cookies host-only, never CDN caches',async()=>{const headers=new Headers({'Cache-Control':'public,max-age=3600'});headers.append('Set-Cookie','sa_student_v45=abc; Path=/api; HttpOnly; Secure; SameSite=Lax; Domain=api.academy.test');headers.append('Set-Cookie','sa_session=; Path=/; Max-Age=0');const res=await proxyApi(req('/api/auth/login',{method:'POST'}),{env,fetcher:async()=>Response.json({success:true},{headers})});assert.equal(res.headers.getSetCookie().length,2);assert.doesNotMatch(res.headers.getSetCookie().join('\n'),/Domain=/i);assert.match(res.headers.get('cache-control'),/no-store/);assert.equal(res.headers.get('cdn-cache-control'),'no-store');});
test('upstream failure remains error, never successful anonymous session',async()=>{const res=await proxyApi(req('/api/auth/session'),{env,fetcher:async()=>{throw new Error('upstream failed');}});assert.equal(res.status,502);assert.equal((await res.json()).success,false);});
test('JSON error status passes through with request identity',async()=>{const res=await proxyApi(req('/api/courses/x'),{env,fetcher:async()=>Response.json({success:false,message:'Database unavailable'},{status:503,headers:{'X-Request-ID':'request-123'}})});assert.equal(res.status,503);assert.equal(res.headers.get('x-request-id'),'request-123');});
test('raw webhook payload streams byte-for-byte through real HTTP upstream',async()=>{
 const payload='{"id": "test-event", "note":"café"}\n';let actual='';
 const server=createServer(async(r,s)=>{for await(const c of r)actual+=c.toString();assert.equal(r.headers['stripe-signature'],'test-signature');s.setHeader('Content-Type','application/json');s.end('{"success":true}');});server.listen(0,'127.0.0.1');await once(server,'listening');
 try{const res=await proxyApi(req('/api/payments/webhooks/stripe',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':'test-signature'},body:payload}),{env:{NODE_ENV:'development',API_PROXY_TARGET:`http://127.0.0.1:${server.address().port}`}});assert.equal((await res.json()).success,true);assert.equal(actual,payload);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
test('encoded traversal cannot escape the fixed /api namespace',async()=>{let called=false;const res=await proxyApi(req('/api/%252e%252e/secrets'),{env,fetcher:async()=>{called=true;}});assert.equal(res.status,400);assert.equal(called,false);});
test('range and binary response metadata survive without buffering/corrupting media',async()=>{const data=Uint8Array.from([0,7,255]);const res=await proxyApi(req('/api/media/123',{headers:{Range:'bytes=1-3'}}),{env,fetcher:async(_,o)=>{assert.equal(o.headers.get('range'),'bytes=1-3');return new Response(data,{status:206,headers:{'Content-Type':'video/mp4','Content-Range':'bytes 1-3/4'}});}});assert.equal(res.status,206);assert.equal(res.headers.get('content-range'),'bytes 1-3/4');assert.deepEqual(new Uint8Array(await res.arrayBuffer()),data);});

test('loopback HTTP exception is confined to explicit local test requests, not hosted review',()=>{
 const env={NODE_ENV:'production',API_PROXY_TARGET:'http://127.0.0.1:5000',API_PROXY_ALLOW_LOCAL_TEST_ONLY:'true'};
 assert.equal(proxyTarget(env,'http://localhost:3000'),'http://127.0.0.1:5000');
 assert.throws(()=>proxyTarget(env,'https://academy.hostingersite.com'));
 assert.throws(()=>proxyTarget({...env,API_PROXY_ALLOW_LOCAL_TEST_ONLY:undefined},'http://localhost:3000'));
});

test('only backend-proved public catalog image may use private browser cache',async()=>{const res=await proxyApi(req('/api/media/'+'a'.repeat(24)+'?w=480'),{env,fetcher:async()=>new Response(Uint8Array.of(1),{headers:{'Content-Type':'image/webp','X-SA-Public-Image':'1'}})});assert.equal(res.headers.get('cache-control'),'private, max-age=300');assert.equal(res.headers.get('cdn-cache-control'),'no-store');assert.equal(res.headers.get('x-sa-public-image'),null);});
test('private receipt image remains no-store without catalog authorization marker',async()=>{const res=await proxyApi(req('/api/media/'+'a'.repeat(24)),{env,fetcher:async()=>new Response(Uint8Array.of(1),{headers:{'Content-Type':'image/webp','Cache-Control':'public,max-age=99999'}})});assert.match(res.headers.get('cache-control'),/no-store/);});
test('public image marker cannot make JSON billing response cacheable',async()=>{const res=await proxyApi(req('/api/payments/mine/invoices'),{env,fetcher:async()=>Response.json({success:true},{headers:{'X-SA-Public-Image':'1'}})});assert.match(res.headers.get('cache-control'),/no-store/);});
