import test from 'node:test';import assert from 'node:assert/strict';
import {compileModule,browserGlobals} from './compile.mjs';import {hookHarness} from './hooks.mjs';
import {subscriptionDisplay} from '../../backend/src/utils/subscriptionDisplay.js';
import {proxyTarget} from '../lib/server/apiProxy.mjs';
const clock=compileModule('../lib/subscriptionClock.ts'),safety=compileModule('../lib/checkoutSafety.ts'),recovery=compileModule('../lib/errorRecovery.ts');
const policy=compileModule('../lib/pagePolicy.ts');
test('only landing and deliberate exceptions are public',()=>{for(const p of ['/','/connection','/login','/register','/terms','/privacy'])assert.equal(policy.publicPage(p),true);for(const p of ['/about','/courses','/team','/billing','/checkout','/home','/admin'])assert.equal(policy.publicPage(p),false);});
test('destination including query and hash survives login URL encoding',()=>{const q=new URL(policy.loginDestination('/courses/test?price=6#lessons'),'https://academy.test');assert.equal(q.pathname,'/login');assert.equal(q.searchParams.get('next'),'/courses/test?price=6#lessons');});
test('development loopback can reach local API without copied Hostinger env',()=>assert.equal(proxyTarget({NODE_ENV:'development'},'http://localhost:3000'),'http://127.0.0.1:5000'));
for(const env of [{NODE_ENV:'production'},{NODE_ENV:'development'}])test('hosted API origin is never guessed '+env.NODE_ENV,()=>assert.throws(()=>proxyTarget(env,'https://academy.test')));
for(const status of ['active','cancelled','expired','past_due','unknown'])for(const at of ['2026-10-03T23:59Z','2026-10-04T00:01Z','2027-10-03T10:00Z','2027-10-03T20:31Z'])test('browser and API day count agree: '+status+' '+at,()=>{const term={status,startsAt:'2026-10-03T20:30Z',endsAt:'2027-10-03T20:30Z'},a=subscriptionDisplay(term,new Date(at)),b=clock.subscriptionClock(term,new Date(at));for(const field of ['remainingDays','durationDays','effectiveStatus'])assert.equal(b[field],a[field]);});
test('checkout key uses cryptographic fallback when randomUUID is unavailable',()=>{let called=0;const key=safety.checkoutId({getRandomValues:bytes=>{called++;bytes.fill(17);return bytes;}});assert.equal(called,1);assert.equal(key,'11'.repeat(24));});
test('checkout refuses an insecure randomness fallback',()=>assert.throws(()=>safety.checkoutId({}),/cryptographic/));
for(const [url,provider] of [['https://checkout.stripe.com/a','stripe'],['https://www.sandbox.paypal.com/a','paypal']])test('approved hosted checkout URL '+provider,()=>assert.equal(safety.checkoutAddress(url,provider),url));
for(const url of ['https://checkout.stripe.com.evil.test','http://checkout.stripe.com/a','https://u:p@checkout.stripe.com','https://checkout.stripe.com:444/a',undefined])test('unsafe checkout URL rejected '+url,()=>assert.throws(()=>safety.checkoutAddress(url,'stripe')));
test('only stale code chunk errors are eligible for automatic reload',()=>{assert.equal(recovery.recoverableChunkError({name:'ChunkLoadError'}),true);assert.equal(recovery.recoverableChunkError({message:'Loading chunk 14 failed.'}),true);for(const message of ['Payment failed','Database connection error','Cannot read properties of undefined'])assert.equal(recovery.recoverableChunkError({message}),false);});
test('stale chunk reload is bounded even when replacement fails',()=>{const m=new Map(),storage={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};assert.equal(recovery.allowChunkReload(storage,'path',1000000),true);assert.equal(recovery.allowChunkReload(storage,'path',1000100),false);assert.equal(recovery.allowChunkReload(storage,'path',1600001),true);});
test('blocked browser storage cannot create a reload loop',()=>assert.equal(recovery.allowChunkReload({getItem(){throw Error('blocked');},setItem(){}},'key'),false));
function nodes(tree){if(!tree)return[];if(Array.isArray(tree))return tree.flatMap(nodes);if(typeof tree!=='object')return[];return[tree,...nodes(tree.props?.children)];}
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
function checkoutFixture(create,recover=async()=>({found:false,order:null})){const h=hookHarness(),browser=browserGlobals(),writes=[],reads=[],navigations=[],m=new Map();browser.window.location.assign=url=>navigations.push(url);const user={id:'student-a',role:'student'};const mod=compileModule('../app/checkout/page.tsx',{imports:{react:h.React,'react/jsx-runtime':h,'next/navigation':{useRouter:()=>({replace(){},push:url=>navigations.push(url)}),useSearchParams:()=>new URLSearchParams('plan=Annual')},'../../components/ApiLoadError':{default:()=>null},'../../components/layout/BackButton':{default:()=>null},'../../components/SiteHeader':{default:()=>null},'../../components/layout/SiteFooter':{default:()=>null},'../../components/auth/AuthProvider':{useAuth:()=>({user,ready:true})},'../../lib/api':{safeStudentNext:x=>x,apiFetch:async(path,opts)=>{if(path==='/payments/methods')return{methods:{stripe:{enabled:true}}};if(path.startsWith('/payments/catalog'))return{purchase:{title:'Annual',offers:[{key:'annual',amountMinor:100,currency:'USD',durationMonths:12}]}};if(path==='/payments/checkout/release')return{released:true,order:{_id:'a'.repeat(24),provider:'stripe',kind:'membership',product:'Annual',status:'expired'},replacementKey:'replacement-test-key-1234567890'};if(path==='/payments/checkout'){writes.push(opts);const data=await create();return data.url&&!data.order?{...data,order:{_id:'a'.repeat(24),provider:'stripe',kind:'membership',product:'Annual',status:'pending'}}:data;}if(path==='/payments/checkout-status'){reads.push(opts);const data=await recover();return {...data,...(data.order?{order:{_id:'a'.repeat(24),provider:'stripe',kind:'membership',product:'Annual',...data.order}}:{})};}throw Error(path);}},'../../lib/money':{money:n=>'$'+n},'../../lib/publicSiteContent':{getPublicSiteContent:async()=>({membershipPlans:[{name:'Annual',price:1,durationMonths:12}]})},'../../lib/checkoutSafety':safety},globals:{...browser,...h.globals,navigator:{onLine:true},sessionStorage:{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}}});h.mount(()=>mod.default());return{h,browser,writes,reads,navigations,pay:()=>nodes(h.tree).find(n=>n.props?.className==='paymentMethod stripe').props.onClick()};}
test('rapid checkout clicks create one request and same key is retained after provider Back',async t=>{const d=deferred(),f=checkoutFixture(()=>d.promise);t.after(()=>f.h.cleanup());await f.h.settle();const one=f.pay(),two=f.pay();await f.h.settle();assert.equal(f.writes.length,1);d.resolve({url:'https://checkout.stripe.com/a'});await Promise.all([one,two]);await f.h.settle();assert.equal(f.navigations.length,1);f.browser.window.dispatchEvent(new Event('pageshow'));await f.h.settle();await f.pay();await f.h.settle();assert.equal(f.writes[0].headers['Idempotency-Key'],f.writes[1].headers['Idempotency-Key']);});
test('checkout timeout releases busy state but never automatically repeats a purchase',async t=>{const f=checkoutFixture(()=>Promise.reject(new Error('timeout')));t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();await f.h.settle();assert.equal(f.writes.length,1);const b=nodes(f.h.tree).find(n=>n.props?.className==='paymentMethod stripe');assert.equal(b.props.disabled,false);assert.equal(f.navigations.length,0);});
const {websiteConfig}=compileModule('../lib/websiteConfig.ts');
for(const raw of [null,undefined,[],{images:{}},{images:'bad',text:[]},{images:[null,'x',{},42],text:{key:12}}])test('malformed historical website content cannot break image rendering: '+JSON.stringify(raw),()=>{const result=websiteConfig(raw);assert.equal(Array.isArray(result.images),true);assert.equal(result.images.length,0);assert.equal(typeof result.text,'object');});
function returnFixture({cancelled=false,respond}={}){
 const h=hookHarness(),b=browserGlobals(),calls=[],user={id:'student-a',role:'student'};
 const mod=compileModule('../app/checkout/return/page.tsx',{imports:{react:h.React,'react/jsx-runtime':h,'next/link':{default:()=>null},'next/navigation':{useRouter:()=>({replace(){}}),useSearchParams:()=>new URLSearchParams('order='+'a'.repeat(24)+(cancelled?'&cancelled=1':''))},'../../../components/auth/AuthProvider':{useAuth:()=>({user,ready:true})},'../../../components/SiteHeader':{default:()=>null},'../../../components/layout/SiteFooter':{default:()=>null},'../../../lib/api':{apiFetch:async(p,o)=>{calls.push({path:p,opts:o});const data=await respond(p,o);return {...data,...(data.order?{order:{_id:'a'.repeat(24),...data.order}}:{})};},isAbortError:e=>e?.name==='AbortError'},'../../../lib/money':{money:n=>'$'+n},'../../../lib/checkoutSafety':safety},globals:{...b,...h.globals,navigator:{onLine:true}}});
 h.mount(()=>mod.default());return{h,b,calls};
}
test('payment return reconciles once and stops polling after server-confirmed payment',async t=>{const f=returnFixture({respond:async()=>({order:{status:'paid',amountMinor:100,currency:'USD',provider:'stripe',kind:'membership'}})});t.after(()=>f.h.cleanup());await f.h.settle();assert.equal(f.calls.length,1);assert.equal(f.calls[0].opts.method,'POST');f.h.run(6000);await f.h.settle();assert.equal(f.calls.length,1);assert.ok(nodes(f.h.tree).some(n=>n.type==='h1'&&n.props.children==='You’re ready to learn.'));});
test('cancelled provider return only reads status and never requests capture',async t=>{const f=returnFixture({cancelled:true,respond:async()=>({order:{status:'pending',amountMinor:100,currency:'USD',provider:'paypal'}})});t.after(()=>f.h.cleanup());await f.h.settle();assert.equal(f.calls.length,1);assert.equal(f.calls[0].opts.method,undefined);assert.equal(f.calls[0].path.endsWith('/confirm'),false);f.h.run(6000);assert.equal(f.calls.length,1);});
test('pending payment confirmation is single-flight even if page events repeat',async t=>{const d=deferred(),f=returnFixture({respond:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();f.b.window.dispatchEvent(new Event('pageshow'));f.b.window.dispatchEvent(new Event('online'));f.h.run(6000);await f.h.settle();assert.equal(f.calls.length,1);d.resolve({order:{status:'paid',amountMinor:100,currency:'USD'}});await f.h.settle();assert.equal(f.calls.length,1);});
test('bad payment response displays retry, not a render exception or success',async t=>{const f=returnFixture({respond:async()=>({})});t.after(()=>f.h.cleanup());await f.h.settle();assert.ok(nodes(f.h.tree).some(n=>n.props?.role==='alert'));assert.ok(nodes(f.h.tree).some(n=>n.type==='button'&&n.props.disabled===false));});

function landingFixture({user=null,pathname='/'}={}){
 const h=hookHarness(),browser=browserGlobals(),routed=[];
 class Element {closest(){return this;}classList={contains:()=>false};}
 class Anchor extends Element {constructor(href){super();this.href=new URL(href,browser.window.location.origin).href;}}
 const mod=compileModule('../components/auth/LandingAuthGate.tsx',{imports:{react:h.React,'next/navigation':{usePathname:()=>pathname,useRouter:()=>({push:x=>routed.push(x),replace:x=>routed.push(x)})},'./AuthProvider':{useAuth:()=>({user,ready:true,signedOut:false,signingOut:false})},'../../lib/pagePolicy':policy},globals:{...browser,Element,HTMLAnchorElement:Anchor}});
 h.mount(()=>mod.default());
 const click=target=>{const event=new Event('click',{cancelable:true});Object.defineProperty(event,'target',{value:target});browser.document.dispatchEvent(event);return event;};
 return{h,click,Anchor,Element,routed};
}
for(const href of ['/about','/courses?category=leadership','#pricing','/#courses'])test('guest landing CTA retains target before sign-in: '+href,t=>{const f=landingFixture();t.after(()=>f.h.cleanup());const event=f.click(new f.Anchor(href));assert.equal(event.defaultPrevented,true);const address=new URL(href,'http://academy.local');assert.equal(new URL(f.routed[0],'http://academy.local').searchParams.get('next'),address.pathname+address.search+address.hash);});
for(const href of ['/','/login','/register','/terms','mailto:info@singhacademy.com','https://www.youtube.com/'])test('essential/external landing link is not trapped in a login loop: '+href,t=>{const f=landingFixture();t.after(()=>f.h.cleanup());const event=f.click(new f.Anchor(href));assert.equal(event.defaultPrevented,false);assert.equal(f.routed.length,0);});
test('verified signed-in landing opens Home and links do not redirect to login',t=>{const f=landingFixture({user:{id:'student-a',role:'student'}});t.after(()=>f.h.cleanup());assert.deepEqual(f.routed,['/home']);assert.equal(f.click(new f.Anchor('/courses')).defaultPrevented,false);});
test('guest team card opens its local preview; only full-profile navigation requires login',t=>{const f=landingFixture();t.after(()=>f.h.cleanup());assert.equal(f.click(new f.Element()).defaultPrevented,false);const button=new f.Element();button.classList.contains=k=>k==='teamCard';assert.equal(f.click(button).defaultPrevented,false);assert.equal(f.routed.length,0);assert.equal(f.click(new f.Anchor('/team')).defaultPrevented,true);assert.equal(new URL(f.routed[0],'http://academy.local').searchParams.get('next'),'/team');});
function apiFixture(fetcher){const b=browserGlobals(),boundary=compileModule('../lib/authBoundary.ts',{globals:b});return{boundary,api:compileModule('../lib/api.ts',{imports:{'./authBoundary':boundary},globals:{...b,fetch:fetcher}})};}
test('landing courses/team/reviews consumers share one network request',async()=>{const d=deferred();let n=0;const f=apiFixture(()=>{n++;return d.promise;});const requests=[f.api.apiFetch('/content/landing'),f.api.apiFetch('/content/landing'),f.api.apiFetch('/content/landing')];d.resolve(Response.json({success:true,courses:[],team:[],reviews:[]}));await Promise.all(requests);assert.equal(n,1);});
test('failed compact session is not immediately retried by API client',async()=>{let n=0;const f=apiFixture(async()=>{n++;return Response.json({success:false,message:'Unavailable'},{status:503});});await assert.rejects(()=>f.api.apiFetch('/auth/session?compact=1'),{status:503});assert.equal(n,1);});
test('explicit logout also fences compact session rechecks',async()=>{let n=0;const f=apiFixture(async()=>{n++;return Response.json({success:true,user:{id:'old'}});});f.boundary.markExplicitLogout('student');assert.equal((await f.api.apiFetch('/auth/session?compact=1')).user,null);assert.equal(n,0);});

test('lost create reply recovers the SAME hosted checkout with read-only lookup and one POST',async t=>{const f=checkoutFixture(async()=>{throw Error('network timeout');},async()=>({found:true,order:{status:'pending'},url:'https://checkout.stripe.com/a'}));t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();await f.h.settle();assert.equal(f.writes.length,1);assert.equal(f.reads.length,1);assert.equal(f.reads[0].headers['Idempotency-Key'],f.writes[0].headers['Idempotency-Key']);assert.equal(f.reads[0].method,undefined);assert.deepEqual(f.navigations,['https://checkout.stripe.com/a']);});
test('lost create reply with completed payment opens receipt status rather than asking for payment again',async t=>{const f=checkoutFixture(async()=>{throw Error('timeout');},async()=>({found:true,order:{_id:'a'.repeat(24),status:'paid'}}));t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();await f.h.settle();assert.equal(f.writes.length,1);assert.deepEqual(f.navigations,['/checkout/return?order='+'a'.repeat(24)]);});
test('unconfirmed checkout offers status check, not a fresh key/new payment',async t=>{const f=checkoutFixture(async()=>{throw Error('timeout');},async()=>({found:true,order:{status:'creating'},creationPending:true}));t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();await f.h.settle();assert.ok(nodes(f.h.tree).some(n=>n.type==='button'&&n.props.children==='Check existing checkout'));assert.equal(nodes(f.h.tree).some(n=>n.props?.children==='Start a new checkout'),false);assert.equal(f.writes.length,1);});
test('provider-confirmed closed checkout can intentionally obtain a fresh request key',async t=>{const f=checkoutFixture(async()=>{throw Error('closed');},async()=>({found:true,order:{status:'expired'}}));t.after(()=>f.h.cleanup());f.browser.window.confirm=()=>true;await f.h.settle();await f.pay();await f.h.settle();const first=f.writes[0].headers['Idempotency-Key'];nodes(f.h.tree).find(n=>n.props?.children==='Start a new checkout').props.onClick();await f.h.settle();await f.pay();assert.notEqual(f.writes[1].headers['Idempotency-Key'],first);});
test('checkout feedback appears immediately and escalates slow provider status without repeating the POST',async t=>{const d=deferred(),f=checkoutFixture(()=>d.promise);t.after(()=>f.h.cleanup());await f.h.settle();const p=f.pay();await f.h.settle();assert.equal(nodes(f.h.tree).find(n=>n.props?.className==='paymentMethod stripe').props.disabled,true);f.h.run(8000);await f.h.settle();assert.ok(nodes(f.h.tree).some(n=>typeof n.props?.children==='string'&&n.props.children.includes('payment provider is taking longer')));assert.equal(f.writes.length,1);d.resolve({url:'https://checkout.stripe.com/a'});await p;});
