/** Execute actual component callbacks with deterministic hooks/HTTP doubles.
 * Separate real Next browser cases live in ui-tests/payments-v60-12.spec.ts. */
import test from 'node:test';import assert from 'node:assert/strict';
import {compileModule,browserGlobals} from './compile.mjs';import {hookHarness} from './hooks.mjs';
const nodes=t=>!t?[]:Array.isArray(t)?t.flatMap(nodes):typeof t==='object'?[t,...nodes(t.props?.children)]:[];
const safety=compileModule('../lib/checkoutSafety.ts');
const presentation=compileModule('../lib/courseAccessPresentation.ts');
const deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject};};
function storage(){const m=new Map();return{get length(){return m.size;},key:i=>[...m.keys()][i]||null,getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),keys:()=>[...m.keys()]};}
const owner='a'.repeat(24),id='b'.repeat(24),attempt={owner,kind:'course',product:'paid-demo',optionKey:'annual',renewalOf:'',provider:'stripe',key:'fixture-checkout-00000001'};
test('unknown checkout identity survives a remount with the same owner/product/provider/key',()=>{const s=storage();safety.saveCheckoutAttempt(s,attempt);assert.equal(safety.readCheckoutAttempt(s,safety.checkoutScope(owner,'course','paid-demo')).key,attempt.key);});
test('browser pending checkout metadata cannot restore a different student identity',()=>{const s=storage();safety.saveCheckoutAttempt(s,attempt);assert.equal(safety.readCheckoutAttempt(s,safety.checkoutScope('other','course','paid-demo')),null);});
test('settled checkout clears only its exact owned order and leaves other account/order attempts',()=>{const s=storage();safety.saveCheckoutAttempt(s,{...attempt,orderId:id});safety.saveCheckoutAttempt(s,{...attempt,owner:'other',orderId:id});safety.saveCheckoutAttempt(s,{...attempt,product:'other-product',orderId:'c'.repeat(24)});safety.clearSettledCheckout(s,owner,id);assert.equal(safety.readCheckoutAttempt(s,safety.checkoutScope(owner,'course','paid-demo')),null);assert.ok(safety.readCheckoutAttempt(s,safety.checkoutScope('other','course','paid-demo')));assert.ok(safety.readCheckoutAttempt(s,safety.checkoutScope(owner,'course','other-product')));});
for(const raw of ['oops','null','{}',JSON.stringify({...attempt,provider:'evil'}),JSON.stringify({...attempt,key:'too-short'}),JSON.stringify({...attempt,orderId:'wrong'}),JSON.stringify({...attempt,owner:'another'})])test('malformed/mis-scoped pending checkout is never accepted: '+raw.slice(0,45),()=>{const s=storage(),key=safety.checkoutScope(owner,'course','paid-demo');s.setItem(key,raw);assert.equal(safety.readCheckoutAttempt(s,key),null);});
test('browser storage exceptions do not fabricate a settled checkout',()=>{const s={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')},removeItem(){throw Error('blocked')}};assert.equal(safety.saveCheckoutAttempt(s,attempt),false);assert.equal(safety.readCheckoutAttempt(s,'scope'),null);assert.doesNotThrow(()=>safety.forgetCheckoutAttempt(s,attempt));});
function courseFixture({free=true,hydrated=true,access={hasAccess:false},enroll=async()=>({success:true})}={}){
 const h=hookHarness(),b=browserGlobals(),calls=[],routes=[],prefetch=[],params={slug:'free-demo'},auth={user:{id:owner,role:'student'},ready:true};let activeHydration=hydrated;
 const router={push:x=>routes.push(x),prefetch:x=>prefetch.push(x)};
 const mod=compileModule('../app/courses/[slug]/page.tsx',{imports:{react:h.React,'react/jsx-runtime':h,'next/navigation':{useParams:()=>params,useRouter:()=>router},'../../../lib/useHydrated':{useHydrated:()=>activeHydration},'../../../components/AcademyImage':{},'../../../components/layout/BackButton':{},'../../../components/SiteHeader':{},'../../../components/layout/SiteFooter':{},'../../../components/ApiLoadError':{},'../../../components/auth/AuthProvider':{useAuth:()=>auth},'../../../lib/courseAccessPresentation':presentation,'../../../lib/useMembershipAccess':{useMembershipAccess:()=>({active:false})},'../../../lib/api':{isAbortError:e=>e?.name==='AbortError',apiFetch:async(path,options)=>{calls.push({path,options});if(path.endsWith('/enroll'))return enroll(path,options);if(path.startsWith('/payments/access'))return access;return{course:{slug:params.slug,title:'Test course',accessType:free?'free':'one_time'},modules:[]};}}},globals:{...b,...h.globals}});
 h.mount(()=>mod.default());return{h,b,auth,params,calls,routes,prefetch,hydrate(){activeHydration=true;h.render();},button:()=>nodes(h.tree).find(n=>n.type==='button'&&n.props.className==='button')};
}
test('free-course route is warmed without automatically enrolling or calling checkout',async t=>{const f=courseFixture();t.after(()=>f.h.cleanup());await f.h.settle();assert.deepEqual(f.prefetch,['/learn/free-demo']);assert.equal(f.calls.some(c=>c.options?.method==='POST'),false);assert.equal(f.calls.some(c=>c.path.includes('payments')),false);});
test('first free-course Start creates one enrollment and remains busy until learning navigation',async t=>{const d=deferred(),f=courseFixture({enroll:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();const button=f.button(),a=button.props.onClick(),b=button.props.onClick();assert.equal(f.calls.filter(c=>c.path.endsWith('/enroll')).length,1);await f.h.settle();assert.equal(f.button().props.disabled,true);d.resolve({success:true});await Promise.all([a,b]);await f.h.settle();assert.deepEqual(f.routes,['/learn/free-demo']);assert.equal(f.button().props.disabled,true);assert.equal(f.calls.some(c=>c.path.startsWith('/payments/')),false);});
test('free Start remains disabled before hydration and cannot lose the first enabled click',async t=>{const f=courseFixture({hydrated:false});t.after(()=>f.h.cleanup());await f.h.settle();assert.equal(f.button().props.disabled,true);await f.button().props.onClick();assert.equal(f.calls.some(c=>c.path.endsWith('/enroll')),false);f.hydrate();await f.button().props.onClick();assert.deepEqual(f.routes,['/learn/free-demo']);});
test('enrollment error shows feedback and releases only the current start lock',async t=>{const f=courseFixture({enroll:async()=>{throw Error('Enrollment unavailable')}});t.after(()=>f.h.cleanup());await f.h.settle();await f.button().props.onClick();await f.h.settle();assert.equal(f.button().props.disabled,false);assert.deepEqual(f.routes,[]);assert.ok(nodes(f.h.tree).some(n=>n.props?.children==='Enrollment unavailable'));});
test('logout/account switch while enrollment is pending prevents late learning navigation',async t=>{const d=deferred(),f=courseFixture({enroll:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();const task=f.button().props.onClick();f.auth.user=null;f.h.render();d.resolve({success:true});await task;assert.deepEqual(f.routes,[]);});
test('changing course while enrollment is pending cancels its stale redirect',async t=>{const d=deferred(),f=courseFixture({enroll:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();const task=f.button().props.onClick();f.params.slug='other-demo';f.h.render();d.resolve({success:true});await task;assert.deepEqual(f.routes,[]);});
test('paid course without access goes to checkout but never creates payment on the detail page',async t=>{const f=courseFixture({free:false});t.after(()=>f.h.cleanup());await f.h.settle();await f.button().props.onClick();assert.deepEqual(f.routes,['/checkout?course=free-demo']);assert.equal(f.calls.some(c=>c.options?.method==='POST'),false);});
test('paid course with verified access only creates its missing enrollment then opens learning',async t=>{const f=courseFixture({free:false,access:{hasAccess:true,enrollment:null}});t.after(()=>f.h.cleanup());await f.h.settle();await f.button().props.onClick();assert.equal(f.calls.filter(c=>c.path.endsWith('/enroll')).length,1);assert.deepEqual(f.routes,['/learn/free-demo']);});
function paymentFixture({create=async()=>({order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'pending'},url:'https://checkout.stripe.com/a'}),release=async()=>{throw Object.assign(Error('Previous payment is uncertain'),{status:409})},recover=async()=>({found:true,order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'creating'}}),saved=storage(),student=owner}={}){
 const h=hookHarness(),b=browserGlobals(),writes=[],reads=[],releases=[],routes=[],user={id:student,role:'student'},query=new URLSearchParams('course=paid-demo'),router={replace(){},push:p=>routes.push(p)};
 b.window.location.assign=p=>routes.push(p);b.window.confirm=()=>true;
 const mod=compileModule('../app/checkout/page.tsx',{imports:{react:h.React,'react/jsx-runtime':h,'next/navigation':{useRouter:()=>router,useSearchParams:()=>query},'../../components/ApiLoadError':{},'../../components/layout/BackButton':{},'../../components/SiteHeader':{},'../../components/layout/SiteFooter':{},'../../components/auth/AuthProvider':{useAuth:()=>({user,ready:true})},'../../lib/checkoutSafety':safety,'../../lib/publicSiteContent':{getPublicSiteContent:async()=>({membershipPlans:[]})},'../../lib/money':{money:n=>String(n)},'../../lib/api':{safeStudentNext:p=>p,apiFetch:async(path,options)=>{if(path==='/payments/methods')return{methods:{stripe:{enabled:true},paypal:{enabled:true}}};if(path.startsWith('/payments/catalog'))return{purchase:{kind:'course',product:'paid-demo',offers:[{key:'annual',amountMinor:14900,currency:'USD',durationMonths:12}]}};if(path==='/payments/checkout/release'){releases.push(options);return release(options);}if(path==='/payments/checkout'){writes.push(options);return create(options);}if(path==='/payments/checkout-status'){reads.push(options);return recover(options);}throw Error(path);}}},globals:{...b,...h.globals,sessionStorage:saved,navigator:{onLine:true}}});
 h.mount(()=>mod.default());return{h,b,writes,reads,releases,routes,saved,user,query,button:p=>nodes(h.tree).find(n=>n.props?.className==='paymentMethod '+p),pay(p='stripe'){return this.button(p).props.onClick();}};
}
test('unresolved Stripe allows selecting PayPal but server release refusal prevents a second payment',async t=>{const f=paymentFixture({create:async()=>{throw Error('timeout')}});t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();await f.h.settle();assert.equal(f.button('paypal').props.disabled,false);await f.pay('paypal');assert.equal(f.releases.length,1);assert.equal(f.writes.length,1);assert.equal(f.reads.length,2);});
test('unresolved purchase fence survives refresh/remount in the same account',async t=>{const saved=storage(),first=paymentFixture({saved,create:async()=>{throw Error('timeout')}});await first.h.settle();await first.pay();first.h.cleanup();const second=paymentFixture({saved});t.after(()=>second.h.cleanup());await second.h.settle();assert.equal(second.button('paypal').props.disabled,false);await second.pay('paypal');assert.equal(second.releases.length,1);assert.equal(second.writes.length,0);});
test('another student cannot inherit a browser pending-checkout key',async t=>{const saved=storage();safety.saveCheckoutAttempt(saved,attempt);const f=paymentFixture({saved,student:'another'});t.after(()=>f.h.cleanup());await f.h.settle();assert.equal(f.button('paypal').props.disabled,false);await f.pay();assert.notEqual(f.writes[0].headers['Idempotency-Key'],attempt.key);});
test('pageshow during unfinished creation cannot unlock a second checkout POST',async t=>{const d=deferred(),f=paymentFixture({create:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();const task=f.pay();f.b.window.dispatchEvent(new Event('pageshow'));await f.h.settle();await f.pay();assert.equal(f.writes.length,1);d.resolve({order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'pending'},url:'https://checkout.stripe.com/a'});await task;});
test('wrong order/provider identity from a malformed response never redirects to payment',async t=>{const wrong={order:{_id:id,provider:'paypal',kind:'course',product:'paid-demo',status:'pending'},url:'https://checkout.stripe.com/a'},f=paymentFixture({create:async()=>wrong,recover:async()=>wrong});t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();assert.deepEqual(f.routes,[]);assert.equal(f.writes.length,1);});
test('paid same-key response opens owned receipt status and clears only its retry metadata',async t=>{const f=paymentFixture({create:async()=>({order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'paid'}})});t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();assert.deepEqual(f.routes,['/checkout/return?order='+id]);assert.equal(f.saved.keys().filter(k=>k.startsWith('sa-checkout-active:')).length,0);});
test('pending stored checkout contains no price, user credentials, card data or access grant',async t=>{const f=paymentFixture();t.after(()=>f.h.cleanup());await f.h.settle();await f.pay();const value=f.saved.getItem(safety.checkoutScope(owner,'course','paid-demo'));const data=JSON.parse(value);for(const field of ['amountMinor','paid','password','card','email','token','hasAccess'])assert.equal(Object.hasOwn(data,field),false);});
for(const fixture of [false,true])test('Next fixture output isolation never changes normal production output: '+fixture,()=>{const d=compileModule('../next.config.ts',{globals:{process:{env:{NODE_ENV:'production',NEXT_PUBLIC_API_URL:'/api',SA_UI_FIXTURE_BUILD:fixture?'true':undefined}}}}).default;assert.equal(d.distDir,fixture?'.next-ui-tests':'.next');assert.equal(d.skipMiddlewareUrlNormalize,true);assert.equal(d.output,fixture?undefined:'standalone');});

test('account switch during checkout response cannot redirect or clear another account attempt',async t=>{const d=deferred(),f=paymentFixture({create:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();const task=f.pay();f.user.id='c'.repeat(24);f.h.render();await f.h.settle();d.resolve({order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'pending'},url:'https://checkout.stripe.com/a'});await task;assert.deepEqual(f.routes,[]);assert.equal(f.reads.length,0);assert.ok(safety.readCheckoutAttempt(f.saved,safety.checkoutScope(owner,'course','paid-demo')));});
test('checkout response after a product change cannot navigate the new page to an old purchase',async t=>{const d=deferred(),f=paymentFixture({create:()=>d.promise});t.after(()=>f.h.cleanup());await f.h.settle();const task=f.pay();f.query.set('course','different-demo');f.h.render();await f.h.settle();d.resolve({order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'pending'},url:'https://checkout.stripe.com/a'});await task;assert.deepEqual(f.routes,[]);assert.equal(f.reads.length,0);});

for(const oldProvider of ['stripe','paypal'])test('explicit verified '+oldProvider+' release enables the other provider using its replacement key',async t=>{
 const saved=storage(),next=oldProvider==='stripe'?'paypal':'stripe';
 safety.saveCheckoutAttempt(saved,{...attempt,provider:oldProvider,orderId:id});
 const replacementKey='server-replacement-key-123456';
 const f=paymentFixture({saved,release:async()=>({released:true,order:{_id:id,provider:oldProvider,kind:'course',product:'paid-demo',status:'cancelled'},replacementKey}),
  create:async options=>({order:{_id:'c'.repeat(24),provider:JSON.parse(options.body).provider,kind:'course',product:'paid-demo',status:'pending'},
   url:next==='stripe'?'https://checkout.stripe.com/a':'https://www.sandbox.paypal.com/checkoutnow?token=fixture'})});
 t.after(()=>f.h.cleanup());await f.h.settle();await f.pay(next);
 assert.equal(f.releases.length,1);assert.equal(f.releases[0].headers['Idempotency-Key'],attempt.key);
 assert.equal(f.writes.length,1);assert.equal(f.writes[0].headers['Idempotency-Key'],replacementKey);
 assert.equal(JSON.parse(f.writes[0].body).provider,next);assert.equal(f.routes.length,1);
});
test('a concurrently paid old checkout routes to receipt and never creates the selected replacement',async t=>{
 const saved=storage();safety.saveCheckoutAttempt(saved,{...attempt,orderId:id});
 const f=paymentFixture({saved,release:async()=>({released:false,order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'paid'}})});
 t.after(()=>f.h.cleanup());await f.h.settle();await f.pay('paypal');
 assert.equal(f.writes.length,0);assert.deepEqual(f.routes,['/checkout/return?order='+id]);
});
test('double-clicking a method switch submits one release and one new checkout',async t=>{
 const saved=storage();safety.saveCheckoutAttempt(saved,{...attempt,orderId:id});
 const d=deferred(),f=paymentFixture({saved,release:()=>d.promise,create:async()=>({order:{_id:'c'.repeat(24),provider:'paypal',kind:'course',product:'paid-demo',status:'pending'},url:'https://www.sandbox.paypal.com/checkoutnow?token=fixture'})});
 t.after(()=>f.h.cleanup());await f.h.settle();const first=f.pay('paypal'),second=f.pay('paypal');
 assert.equal(f.releases.length,1);assert.equal(f.writes.length,0);
 d.resolve({released:true,order:{_id:id,provider:'stripe',kind:'course',product:'paid-demo',status:'expired'},replacementKey:'server-replacement-key-123456'});
 await Promise.all([first,second]);assert.equal(f.writes.length,1);
});
