/** Executable SSR snapshot/auth navigation assertions. These exercise actual code
 * using hook doubles; the separate Playwright suite performs real React hydration. */
import test from 'node:test';import assert from 'node:assert/strict';
import {compileModule,browserGlobals} from './compile.mjs';import {hookHarness} from './hooks.mjs';
import {proxyTarget} from '../lib/server/apiProxy.mjs';
const treeNodes=tree=>!tree?[]:Array.isArray(tree)?tree.flatMap(treeNodes):typeof tree==='object'?[tree,...treeNodes(tree.props?.children)]:[];
const policy=compileModule('../lib/pagePolicy.ts');const {safeStudentNext}=compileModule('../lib/studentDestination.ts');
for(const [input,want] of [[undefined,'/home'],[null,'/home'],['/','/home'],['/login','/home'],['/register?next=/about','/home'],['/about','/about'],['/courses?tag=public%20speaking','/courses?tag=public%20speaking'],['/#courses','/courses'],['/#pricing','/academy'],['/#reviews','/reviews']])test('safe sign-in destination '+input,()=>assert.equal(safeStudentNext(input),want));
for(const value of ['https://evil.test','//evil.test','/\\evil.test','/%2f%2fevil.test','/%61dmin','/ADMIN','/super-admin','/x/../login','/%00evil','/%255c%255cevil.test','/api/auth/login'])test('dangerous/loop auth target rejected '+value,()=>assert.equal(safeStudentNext(value),'/home'));
const request=(path,cookie='')=>new Request('http://localhost:3000'+path,{headers:{cookie}});
const env={NODE_ENV:'development',API_PROXY_TARGET:'http://127.0.0.1:5000'},cookie='sa_student_v45='+'b'.repeat(64);
const session=compileModule('../lib/server/pageSession.ts',{imports:{'../pagePolicy':policy,'./apiProxy.mjs':{proxyTarget}}});
const learner={id:'student-a',role:'student',name:'Learner'};
for(const [path,destination]of [['/','/home'],['/login','/home'],['/register','/home'],['/login?next=%2Fabout','/about'],['/login?next=%2F','/home'],['/register?next=%2Fcourses','/courses']])test('server verified student skips auth/landing: '+path,async()=>{const out=await session.pageSession(request(path,cookie),env,async()=>Response.json({success:true,user:learner}));assert.equal(out.redirect,destination);});
for(const path of ['/','/login','/register'])test('guest public entry supplies one deterministic anonymous hydration snapshot: '+path,async()=>{let reads=0;const out=await session.pageSession(request(path),env,async()=>{reads++;throw Error('No guest network');});assert.equal(out.session.verified,true);assert.equal(out.session.user,null);assert.equal(reads,0);});
for(const path of ['/','/login?next=%2Fabout'])test('explicit logout prevents stale server cookie auto-login on '+path,async()=>{let reads=0;const out=await session.pageSession(request(path,cookie+'; sa_logout_student=1'),env,async()=>{reads++;return Response.json({success:true,user:learner});});assert.equal(out.redirect,undefined);assert.equal(out.session.user,null);assert.equal(reads,0);});
for(const path of ['/','/login'])test('temporary backend failure keeps public entry available but unresolved: '+path,async()=>{const out=await session.pageSession(request(path,cookie),env,async()=>Response.json({success:false},{status:503}));assert.equal(out.redirect,undefined);assert.equal(out.unavailable,undefined);assert.equal(out.session,undefined);});
for(const path of ['/admin/login','/super-admin/login'])test('staff entry verifies only its own portal '+path,async()=>{const portal=path.startsWith('/super')?'super_admin':'client_admin';const out=await session.pageSession(request(path,`sa_${portal}_v45=`+'c'.repeat(64)),env,async()=>Response.json({success:true,user:{id:'staff',role:portal}}));assert.equal(out.redirect,path.replace('/login',''));});

test('useHydrated uses identical false server/hydration snapshot even if the browser snapshot is true',()=>{const calls=[];const mod=compileModule('../lib/useHydrated.ts',{imports:{react:{useSyncExternalStore:(subscribe,browser,server)=>{calls.push({subscribe,browser,server});return server();}}}});assert.equal(mod.useHydrated(),false);assert.equal(mod.useHydrated(),false);assert.equal(calls[0].server(),false);assert.equal(calls[0].browser(),true);assert.equal(calls[0].server,calls[1].server);assert.equal(calls[0].subscribe,calls[1].subscribe);});
test('late nested auth hydration reads immutable server seed, not already-updated browser state',()=>{
 const seed={portal:'student',user:null,ready:false,enrollment:null,error:''};const live={portal:'student',user:null,ready:true,sessionError:'',signedOut:true,signingOut:false,hydrationState:seed};let hydrated=false;
 const mod=compileModule('../components/auth/AuthProvider.tsx',{imports:{react:{createContext:()=>({}),useContext:()=>live},'react/jsx-runtime':{},'next/navigation':{},'../../lib/api':{},'../../lib/useHydrated':{useHydrated:()=>hydrated},'../../lib/authNavigation':{},'../../lib/authBoundary':{}}});
 assert.equal(mod.useAuth().ready,false);assert.equal(mod.useAuth().signedOut,false);live.user=learner;assert.equal(mod.useAuth().user,null);hydrated=true;assert.equal(mod.useAuth().user,learner);
});
test('late website text/image hydration sees exact SSR defaults, then live CMS data',()=>{const content={text:{title:'Changed remotely'},images:[{src:'/old.jpg',url:'/new.jpg'}]};let hydrated=false;const mod=compileModule('../components/WebsiteContent.tsx',{imports:{react:{createContext:()=>({}),useContext:()=>content},'react/jsx-runtime':{},'./auth/AuthProvider':{},'../lib/publicSiteContent':{},'../lib/websiteConfig':{},'../lib/useHydrated':{useHydrated:()=>hydrated}}});assert.equal(Object.keys(mod.useWebsiteContent().text).length,0);assert.equal(mod.useWebsiteContent().images.length,0);hydrated=true;assert.equal(mod.useWebsiteContent(),content);});

test('Back inside an autofilled login form is explicitly non-submit and replaces with public landing',()=>{const calls=[],h=hookHarness(),b=browserGlobals();b.window.history={length:12};const mod=compileModule('../components/layout/BackButton.tsx',{imports:{'react/jsx-runtime':h,'next/navigation':{useRouter:()=>({replace:p=>calls.push(['replace',p]),back:()=>calls.push(['back']),push:p=>calls.push(['push',p])})}},globals:b});const button=mod.default({fallback:'/',mode:'destination'});assert.equal(button.props.type,'button');button.props.onClick();assert.deepEqual(calls,[['replace','/']]);});
for(const [role,path]of [['student','/'],['client_admin','/admin/login'],['super_admin','/super-admin/login']])test('one auth-boundary document redirect for '+role,()=>{const b=browserGlobals(),routes=[];b.window.location.replace=path=>routes.push(path);const mod=compileModule('../lib/authNavigation.ts',{globals:b});mod.replaceAuthDocument(mod.logoutDestination(role));assert.deepEqual(routes,[path]);});
test('auth document redirect refuses foreign origin',()=>{const b=browserGlobals(),paths=[];b.window.location.replace=p=>paths.push(p);const mod=compileModule('../lib/authNavigation.ts',{globals:b});assert.throws(()=>mod.replaceAuthDocument('https://evil.test/'),/Invalid authentication/);assert.deepEqual(paths,[]);});

function loginFixture(next='/about'){
 const h=hookHarness(),b=browserGlobals(),routes=[],writes=[];let resolve;const pending=new Promise(r=>resolve=r);
 class FormDataMock{get(key){return {email:'test@example.invalid',password:'TEST-NOT-A-REAL-PASSWORD'}[key];}}
 const mod=compileModule('../app/login/page.tsx',{imports:{react:h.React,'react/jsx-runtime':h,'next/link':{},'../auth.css':{},'../../components/AcademyImage':{},'../../components/layout/BackButton':{},'../../components/auth/PasswordField':{},'next/navigation':{useRouter:()=>({}),useSearchParams:()=>new URLSearchParams({next})},'../../lib/api':{safeStudentNext,apiFetch:(path,options)=>{writes.push({path,options});return pending;}},'../../lib/authNavigation':{replaceAuthDocument:p=>routes.push(p)},'../../components/auth/AuthProvider':{useAuth:()=>({user:null,ready:true,signedOut:true})}},globals:{...h.globals,...b,FormData:FormDataMock}});
 h.mount(()=>mod.default());return {h,routes,writes,resolve,form:()=>treeNodes(h.tree).find(x=>x.type==='form')};
}
test('intentional login double-click submits once and goes to intended page using form data',async t=>{const f=loginFixture('/events');t.after(()=>f.h.cleanup());const e={preventDefault(){},currentTarget:{}};const first=f.form().props.onSubmit(e),second=f.form().props.onSubmit(e);await f.h.settle();assert.equal(f.writes.length,1);assert.equal(JSON.parse(f.writes[0].options.body).email,'test@example.invalid');const button=treeNodes(f.h.tree).find(n=>n.props?.className==='authButton');assert.equal(button.props.disabled,true);assert.equal(button.props['aria-busy'],true);f.resolve({success:true,user:learner});await Promise.all([first,second]);await f.h.settle();assert.deepEqual(f.routes,['/events']);});
test('login next=/ goes to signed-in home rather than marketing landing',async t=>{const f=loginFixture('/');t.after(()=>f.h.cleanup());const promise=f.form().props.onSubmit({preventDefault(){},currentTarget:{}});f.resolve({success:true,user:learner});await promise;assert.deepEqual(f.routes,['/home']);});
