'use client';
import {useWebsiteContent,websiteText} from "../../components/WebsiteContent";

import {money} from '../../lib/money';
import {getPublicSiteContent} from '../../lib/publicSiteContent';
import ApiLoadError from '../../components/ApiLoadError';
import Link from 'next/link';
import {useEffect,useState} from 'react';import PageShell from '../../components/layout/PageShell';
export default function Page(){const website=useWebsiteContent();const[plans,setPlans]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);useEffect(()=>{let live=true;setLoading(true);setError('');getPublicSiteContent(revision>0).then(content=>{if(live){const p=content.membershipPlans;setPlans(Array.isArray(p)?p.filter((x:any)=>x.active!==false):[]);}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[revision]);return <PageShell kicker={websiteText(website,"academy-001","FULL ACADEMY ACCESS")} title={websiteText(website,"academy-002","One membership. A broader learning library.")} intro={websiteText(website,"academy-003","Choose Academy access when you want more than a single course.")}><section className="contentWrap contentGrid">{error&&<ApiLoadError message={error} onRetry={()=>setRevision(n=>n+1)}/>} {loading&&<p role="status">Loading Academy Plans…</p>}{!loading&&!error&&!plans.length&&<div className="emptyState">No Academy Plans are currently published.</div>}{plans.map((p:any,i:number)=><article className="contentCard" key={p.name||i}><span className="kicker">{websiteText(website,"academy-004","MEMBERSHIP")}</span><h3>{p.name}</h3>{p.price!==undefined&&<h4>{money(p.price,p.currency||'USD')}</h4>}<p>{p.durationMonths??(p.period==='year'?12:1)}{websiteText(website,"academy-005"," month(s) of access · one payment · no automatic renewal")}</p><p>{p.description||'Academy membership access.'}</p>{Array.isArray(p.features)&&p.features.length>0&&<ul>{p.features.map((f:string,j:number)=><li key={j}>{f}</li>)}</ul>}<Link className="button" href={"/checkout?plan="+encodeURIComponent(p.name)}>{websiteText(website,"academy-006","Choose membership")}</Link></article>)}</section></PageShell>}
