import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {runSecurityAudit,transientAuditFailure} from '../security-audit.mjs';import {releaseCommandChecks,runReleaseChecks} from '../release-check.mjs';
const zero={status:0,stdout:JSON.stringify({metadata:{vulnerabilities:{info:0,low:0,moderate:0,high:0,critical:0,total:0}},vulnerabilities:{}}),stderr:''};
const failure={status:1,stdout:JSON.stringify({error:{code:'ENOTFOUND',summary:'registry unavailable'}}),stderr:'getaddrinfo ENOTFOUND registry.npmjs.org'};
const quiet={log(){},error(){}};
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'sa-audit-transport-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const scope of ['','backend','frontend']){fs.mkdirSync(path.join(root,scope),{recursive:true});fs.writeFileSync(path.join(root,scope,'package.json'),JSON.stringify({version:'60.15.0',engines:{node:'22.x || 24.x'}}));if(scope)fs.writeFileSync(path.join(root,scope,'package-lock.json'),'{}');}return root;}
test('transient DNS failure retries same four scopes, succeeds only after actual complete reports',t=>{const root=fixture(t);let calls=0;const delays=[];const report=runSecurityAudit({project:root,logger:quiet,sleep:ms=>delays.push(ms),execute:()=>++calls===1?failure:zero});assert.equal(calls,5);assert.equal(report.status,'passed');assert.equal(report.scans[0].attempts.length,2);assert.equal(report.scans[0].attempts[0].status,'failed');assert.deepEqual(delays,[1500]);});
test('persistent DNS never becomes zero; bounded attempts and every scope remains failed',t=>{const root=fixture(t);let calls=0;const report=runSecurityAudit({project:root,logger:quiet,sleep(){},execute:()=>{calls++;return failure;}});assert.equal(calls,12);assert.equal(report.status,'failed');assert.ok(report.scans.every(s=>s.status==='failed'&&s.vulnerabilities===null&&s.attempts.length===3));});
for(const level of ['info','low','moderate','high','critical'])test('a complete '+level+' finding never triggers transport retry',t=>{const root=fixture(t),data=JSON.parse(zero.stdout);data.metadata.vulnerabilities[level]=1;data.metadata.vulnerabilities.total=1;const found={...zero,status:1,stdout:JSON.stringify(data),stderr:'ENOTFOUND in irrelevant package text'};assert.equal(transientAuditFailure(found),false);let calls=0;const report=runSecurityAudit({project:root,logger:quiet,sleep(){assert.fail('never retry findings');},execute:()=>{calls++;return found;}});assert.equal(calls,4);assert.equal(report.status,'failed');});
test('malformed successful JSON without transport error fails once per scope',t=>{const root=fixture(t);let calls=0;const report=runSecurityAudit({project:root,logger:quiet,sleep(){assert.fail();},execute:()=>{calls++;return{...zero,stdout:'broken'};}});assert.equal(calls,4);assert.equal(report.status,'failed');});
test('local command does not repeat raw audits and never claims real integration/handover',t=>{const root=fixture(t),commands=releaseCommandChecks(root);assert.equal(commands.filter(c=>c[2][0]==='audit').length,0);assert.equal(commands.filter(c=>c[2].join(' ')==='run verify').length,1);const r=runReleaseChecks({root,logger:quiet,execute(){}});assert.equal(r.status,'passed');assert.equal(r.handoverReady,false);assert.ok(r.notCovered.some(x=>/Real MongoDB/.test(x)));});
